import React, { useState } from "react";
// import { Link } from "react-router-dom";
import CategoryItems from "./CategoryItems";
import styles from "./Category.module.css";

const categoryItems = [
  {
    icon: "fashion",
    title: "패션의류/잡화",
    submenu: [
      {
        title: "여성패션",
        submenu: [
          { title: "의류" },
          { title: "속옷/잠옷" },
          { title: "신발" },
          { title: "가방/잡화" },
        ],
      },
      {
        title: "남성패션",
        submenu: [
          { title: "의류" },
          { title: "속옷/잠옷" },
          { title: "신발" },
          { title: "가방/잡화" },
        ],
      },
      {
        title: "남녀 공용 의류",
        submenu: [
          { title: "티셔츠" },
          { title: "맨투맨/후드티" },
          { title: "셔츠" },
          { title: "바지" },
          { title: "트레이닝복" },
          { title: "후드집업/집업류" },
          { title: "니트류/조끼" },
          { title: "아우터" },
          { title: "테마의류" },
          { title: "커플룩/패밀리룩" },
          { title: "빅사이즈" },
        ],
      },
      {
        title: "유아동패션",
        submenu: [{ title: "베이비" }, { title: "여아" }, { title: "남아" }],
      },
    ],
  },
  {
    icon: "beauty",
    title: "뷰티",
    submenu: [
      {
        title: "명품뷰티",
      },
      {
        title: "스킨케어",
        submenu: [
          { title: "스킨" },
          { title: "로션" },
          { title: "에센스/세럼/앰플" },
          { title: "미스트" },
          { title: "오일" },
          { title: "크림/올인원" },
          { title: "기초세트" },
          { title: "마스크/팩" },
          { title: "선케어/태닝" },
        ],
      },
      {
        title: "클린/비건뷰티",
        submenu: [
          { title: "스킨케어" },
          { title: "메잌업" },
          { title: "네일&툴" },
        ],
      },
      {
        title: "클렌징/필링",
        submenu: [
          { title: "클렌징 폼" },
          { title: "클렌징 젤/파우더" },
          { title: "클렌징 비누" },
          { title: "클렌징 오일" },
          { title: "클렌징 워터" },
          { title: "립/아이리무버" },
          { title: "클렌징 티슈/시트" },
          { title: "클렌징 로션/크림" },
          { title: "클렌징세트" },
          { title: "스크럽/필링" },
        ],
      },
      { title: "더마코스메틱" },
      {
        title: "메이크업",
        submenu: [
          { title: "베이스 메이크업" },
          { title: "아이 메이크업" },
          { title: "립 메이크업" },
          { title: "치크메이크업" },
          { title: "멀티메이크업" },
          { title: "바이메이크업" },
        ],
      },
      {
        title: "향수",
        submenu: [
          { title: "여성향수" },
          { title: "남성향수" },
          { title: "남녀공용향수" },
          { title: "고체향수" },
          { title: "드레스퍼퓸" },
        ],
      },
      {
        title: "남성화장품",
        submenu: [
          { title: "남성스킨케어" },
          { title: "남성메이크업" },
          { title: "남성화장품세트" },
          { title: "남성 헤어케어" },
          { title: "남성 바디케어" },
          { title: "남성 쉐이빙 케어" },
        ],
      },
      {
        title: "네일",
        submenu: [
          { title: "네일팁/스티커" },
          { title: "일반네일" },
          { title: "젤네일" },
          { title: "큐티클/영양" },
          { title: "네일케어도구" },
          { title: "네일아트소품/도구" },
          { title: "네일세트" },
        ],
      },
      {
        title: "뷰티소품",
        submenu: [
          { title: "화장솜/면봉" },
          { title: "아이소품" },
          { title: "페이스소품" },
          { title: "클렌징소품" },
          { title: "헤어소품" },
          { title: "피부관리기" },
          { title: "용기/거울/기타소품" },
        ],
      },
      {
        title: "어린이화장품",
        submenu: [
          { title: "메이크업" },
          { title: "향수" },
          { title: "네일케어" },
          { title: "세트/키트" },
        ],
      },
      { title: "로드샵" },
      {
        title: "헤어",
        submenu: [
          { title: "샴푸" },
          { title: "린스/컨디셔너" },
          { title: "트리트먼트/팩/앰플" },
          { title: "헤어에센스/오일" },
          { title: "헤어스타일링" },
          { title: "헤어세트" },
          { title: "염색/파마" },
        ],
      },
      {
        title: "바디",
        submenu: [
          { title: "샤워/입욕용품" },
          { title: "바디로션/크림" },
          { title: "핸드/풋/데오" },
          { title: "제모/슬리밍/청결제" },
        ],
      },
      {
        title: "선물세트/키트",
        submenu: [{ title: "선물세트" }, { title: "여행용키트" }],
      },
    ],
  },
  {
    icon: "child",
    title: "출산/유아동",
    submenu: [
      {
        title: "유아동패션",
        submenu: [{ title: "베이비" }, { title: "여아" }, { title: "남아" }],
      },
      {
        title: "기저귀",
        submenu: [
          { title: "일회용기저귀" },
          { title: "수영장기저귀" },
          { title: "천기저귀/액세서리" },
          { title: "배변훈련팬티" },
          { title: "기저귀케익" },
          { title: "기저귀크림/파우더" },
          { title: "기저귀매트" },
          { title: "기저귀통/봉투" },
          { title: "기저귀가방" },
        ],
      },
      {
        title: "물티슈",
        submenu: [
          { title: "물티슈" },
          { title: "건티슈" },
          { title: "물티슈액세서리" },
        ],
      },
      {
        title: "분유/어린이식품",
        submenu: [
          { title: "분유" },
          { title: "이유식" },
          { title: "미음/죽/분말" },
          { title: "양념/식재료" },
          { title: "국/반찬" },
          { title: "간식/음료" },
        ],
      },
      {
        title: "어린이 건강식품",
        submenu: [
          { title: "비타민/미네랄" },
          { title: "홍삼" },
          { title: "칼슘" },
          { title: "유산균/초유" },
          { title: "오메가" },
          { title: "기타 건강식품" },
        ],
      },
      {
        title: "수유용품",
        submenu: [
          { title: "젖병" },
          { title: "젖꼭지" },
          { title: "노리개젖꼭지" },
          { title: "치발기" },
          { title: "모유저장팩" },
          { title: "분유케이스/저장팩" },
          { title: "젖병세척용품" },
          { title: "젖병소독기/건조대" },
          { title: "분유보관용기" },
          { title: "수유패드" },
          { title: "유축기" },
          { title: "모유촉진제" },
          { title: "유두보호/젖몸살용품" },
          { title: "더보기" },
        ],
      },
      {
        title: "이유용품/유아식기",
        submenu: [
          { title: "이유식용품" },
          { title: "턱받이" },
          { title: "빨대컵/유아컵" },
          { title: "유아식기/캐릭터식기" },
          { title: "도시락/물병/보냉팩" },
          { title: "스푼/포크/젖가락" },
          { title: "유아식탁/부스터" },
        ],
      },
      {
        title: "매트/안전용품",
        submenu: [
          { title: "일반매트" },
          { title: "퍼즐매트" },
          { title: "폴더매트" },
          { title: "벽매트" },
          { title: "DIY/시공매트" },
          { title: "유아안전문" },
          { title: "모서리/코너보호대" },
          { title: "손낌방지용품" },
          { title: "잠금장치/커버" },
          { title: "미끄럼방지용품" },
          { title: "침대가드" },
          { title: "뒤집기방지쿠션" },
          { title: "머리/무릎보호대" },
          { title: "더보기" },
        ],
      },
      {
        title: "유모차/웨건",
        submenu: [
          { title: "디럭스유모차" },
          { title: "절충형유모차" },
          { title: "휴대용유모차" },
          { title: "쌍둥이유모차" },
          { title: "웨건" },
          { title: "유모차/웨건액세서리" },
        ],
      },
      {
        title: "카시트",
        submenu: [
          { title: "신생아바구니카시트" },
          { title: "영유아카시트" },
          { title: "주니어카시트" },
          { title: "부스터카시트" },
          { title: "카시트액세서리" },
        ],
      },
      {
        title: "아기띠/외출용품",
        submenu: [
          { title: "아기띠" },
          { title: "올인원 아기띠" },
          { title: "힙시트" },
          { title: "트레킹캐리어" },
          { title: "포대기/처네" },
          { title: "슬링" },
          { title: "아기띠액세서리" },
          { title: "기저귀가방" },
          { title: "기저귀/약파우치" },
          { title: "보닝백/런치백" },
        ],
      },
      {
        title: "욕실용품/스킨케어",
        submenu: [
          { title: "유아워시/샴푸" },
          { title: "유아구강케어" },
          { title: "유아스킨케어" },
          { title: "기저귀크림/파우더" },
          { title: "유아욕조/목욕의자" },
          { title: "유아목욕용품" },
          { title: "유아타올" },
          { title: "유아변기" },
          { title: "선케어/야외활동케어" },
          { title: "어린이화장품" },
        ],
      },
      {
        title: "위생/건강/세제",
        submenu: [
          { title: "위생용품" },
          { title: "유아향균지퍼팩" },
          { title: "배변훈련팬티" },
          { title: "건강용품" },
          { title: "유아세제/세정제" },
          { title: "야외활동용품" },
        ],
      },
      {
        title: "유아동침구",
        submenu: [
          { title: "낮잠이불" },
          { title: "겉싸개/속싸개" },
          { title: "유아이불" },
          { title: "베개/바디필로우" },
          { title: "유아담요/블랭킷" },
          { title: "유아 요/방수요" },
          { title: "침구세트" },
        ],
      },
      {
        title: "유아가구/인테리어",
        submenu: [
          { title: "유아동침대" },
          { title: "유아의자/소파" },
          { title: "수납/정리함" },
          { title: "공부상/책상" },
          { title: "유아책상/책꽂이" },
          { title: "수면등/수유등" },
          { title: "유아키재기스티커" },
        ],
      },
      {
        title: "완구/교구",
        submenu: [
          { title: "연령별완구" },
          { title: "캐릭터별완구" },
          { title: "신생아/영아완구" },
          { title: "블록놀이" },
          { title: "역할놀이" },
          { title: "로봇/작동완구" },
          { title: "인형" },
          { title: "물놀이/계절완구" },
          { title: "승용완구" },
          { title: "실내대형완구" },
          { title: "스포츠/야외완구" },
          { title: "STEAM/학습완구" },
          { title: "보드게임" },
          { title: "더보기" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "food",
    title: "식품",
    submenu: [
      { title: "유기농/친환경 전문관" },
      {
        title: "과일",
        submenu: [
          { title: "사과/배" },
          { title: "귤/한라봉/감귤류" },
          { title: "감/홍시/곶감" },
          { title: "키위/참다래" },
          { title: "토마토/자두/복숭아/포도" },
          { title: "수박/메론/참외" },
          { title: "딸기/블루베리/베리류" },
          { title: "바나나/오렌지/파인애플" },
          { title: "자몽/레몬/라임/석류" },
          { title: "망고/체리/아보카도/기타" },
          { title: "냉동과일/간편과일" },
          { title: "과일선물세트" },
        ],
      },
      {
        title: "견과/건과",
        submenu: [
          { title: "땅콩/호두" },
          { title: "밤/잣/은행" },
          { title: "아몬드/피스타치오" },
          { title: "기타견과류" },
          { title: "호박씨/해바라기씨" },
          { title: "기타씨앗" },
          { title: "혼합견과/세트" },
          { title: "건과일/건채소" },
          { title: "과일가루" },
        ],
      },
      {
        title: "채소",
        submenu: [
          { title: "두부/콩나물" },
          { title: "감자/고구마" },
          { title: "당근/뿌리채소" },
          { title: "오이/고추/열매채소" },
          { title: "양파/마늘/파" },
          { title: "배추/무/김장채소" },
          { title: "시금치/나물/잎줄기채소" },
          { title: "상추/깻잎/쌈채소" },
          { title: "샐러드/손질채소" },
          { title: "새송이/버섯류" },
          { title: "인삼/건강차재료" },
          { title: "기타채소" },
          { title: "건나물/건채소" },
          { title: "더보기" },
        ],
      },
      {
        title: "쌀/잡곡",
        submenu: [
          { title: "백미" },
          { title: "현미/찹쌀/흑미" },
          { title: "기능성쌀/기타쌀" },
          { title: "콩/팥/보리" },
          { title: "조/수수/깨" },
          { title: "기타잡곡/혼합곡" },
          { title: "슈퍼곡물" },
          { title: "기타씨앗" },
          { title: "쌀/잡곡 가루" },
          { title: "곡류선물세트" },
        ],
      },
      {
        title: "축산/계란",
        submenu: [
          { title: "소고기" },
          { title: "돼지고기" },
          { title: "닭/오리고기" },
          { title: "양/말고기" },
          { title: "기타 육고기" },
          { title: "계란/알류/가공란" },
          { title: "축산선물세트" },
        ],
      },
      {
        title: "수산물/건어물",
        submenu: [
          { title: "생선" },
          { title: "오징어/낙지/연체류" },
          { title: "새우/게/갑각류" },
          { title: "전복/굴/조개류" },
          { title: "멸치/다시팩/기타" },
          { title: "김/미역/해조류" },
          { title: "건오징어/쥐포/어포" },
          { title: "황태/진미채" },
          { title: "생선알" },
          { title: "기타수산물/건어물" },
          { title: "수산물선물세트" },
        ],
      },
      {
        title: "생수/음료",
        submenu: [
          { title: "생수" },
          { title: "탄산수" },
          { title: "과일/야채음료" },
          { title: "탄산/스포츠음료" },
          { title: "커피음료/차음료" },
          { title: "두유" },
          { title: "냉장우유" },
          { title: "멸균우유" },
          { title: "숙취/건강음료" },
          { title: "어린이음료" },
          { title: "음료선물세트" },
          { title: "무/비알콜음료" },
          { title: "전통주" },
        ],
      },
      {
        title: "커피/원두차",
        submenu: [
          { title: "커피믹스" },
          { title: "원두/생두" },
          { title: "캡슐/더치/티백" },
          { title: "녹차/메밀차" },
          { title: "둥글레/옥수수차" },
          { title: "보리/우엉/결명차" },
          { title: "도라지/작두콩차" },
          { title: "홍차/밀크티" },
          { title: "유자/과일차" },
          { title: "율무/전통차" },
          { title: "허브/콤부/꽃차" },
          { title: "코코아/라떼/기타분말" },
          { title: "커피/차 선물세트" },
          { title: "더보기" },
        ],
      },
      {
        title: "과자/초콜릿/시리얼",
        submenu: [
          { title: "과자" },
          { title: "비스킷/크래커" },
          { title: "쿠키/파이" },
          { title: "전통과자/떡" },
          { title: "초콜릿" },
          { title: "젤리/캐러멜" },
          { title: "사탕/껌" },
          { title: "시리얼" },
          { title: "베이커리/잼" },
          { title: "육포/원물간식" },
          { title: "과자/간식세트" },
          { title: "어린이간식" },
        ],
      },
      {
        title: "면/통조림/가공식품",
        submenu: [
          { title: "라면/컵라면" },
          { title: "면류/파스타" },
          { title: "참치/햄/통조림" },
          { title: "즉석밥/누룽지" },
          { title: "카레/짜장/양념" },
          { title: "즉석국/간편조리" },
        ],
      },
      {
        title: "가루/조미료/오일",
        submenu: [
          { title: "가루/분말류" },
          { title: "설탕/소금/조미료" },
          { title: "식용유/오일" },
        ],
      },
      {
        title: "장/소스/드레싱/식초",
        submenu: [
          { title: "장류" },
          { title: "케찹/마요네즈" },
          { title: "머스타드" },
          { title: "소스" },
          { title: "드레싱" },
          { title: "식초/미림" },
          { title: "물엿/올리고당/조청" },
          { title: "육수/액젓" },
          { title: "꿀" },
        ],
      },
      {
        title: "유제품/아이스크림",
        submenu: [
          { title: "냉장우유" },
          { title: "멸균우유" },
          { title: "두유" },
          { title: "요구르트" },
          { title: "치즈" },
          { title: "버터/마가린" },
          { title: "생크림/휘핑크림" },
          { title: "연유" },
          { title: "기타유가공품" },
          { title: "유제품가정배달" },
          { title: "아이스크림" },
          { title: "기타 디저트" },
        ],
      },
      {
        title: "냉장/냉동/간편요리",
        submenu: [
          { title: "밀키트" },
          { title: "즉석밥/볶음밥" },
          { title: "즉석국/탕/찌개" },
          { title: "고기/해물/기타요리" },
          { title: "면류" },
          { title: "떡류" },
          { title: "만두/돈까스/치킨" },
          { title: "분식/피자/핫도그" },
          { title: "김치/젓갈/장류" },
          { title: "반찬/절임" },
          { title: "햄/어묵/맛살" },
          { title: "두부/샐러드/도시락" },
        ],
      },
      {
        title: "건강식품",
        submenu: [
          { title: "건강기능식품" },
          { title: "성인용 건강식품" },
          { title: "여성용 건강식품" },
          { title: "남성용 건강식품" },
          { title: "임산부 건강식품" },
          { title: "시니어 건강식품" },
          { title: "어린이 건강식품" },
          { title: "홍삼/인삼" },
          { title: "건강즙/음료" },
          { title: "비타민/미네랄" },
          { title: "영양제" },
          { title: "헬스보충식품" },
          { title: "다이어트/이너뷰티" },
          { title: "더보기" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "kitchen",
    title: "주방용품",
    submenu: [
      {
        title: "주방가전",
        submenu: [
          { title: "전기밥솥" },
          { title: "전자레인지" },
          { title: "오븐" },
          { title: "가스레인지" },
          { title: "전기레인지" },
          { title: "식기세척/건조기" },
          { title: "믹서기/블렌더" },
          { title: "커피메이커/머신" },
          { title: "빙수기/제빙기" },
          { title: "전기포트" },
          { title: "에어프라이어" },
          { title: "튀김기" },
          { title: "토스터" },
          { title: "더보기" },
        ],
      },
      {
        title: "냄비/프라이팬",
        submenu: [
          { title: "냄비/뚝배기" },
          { title: "프라이팬" },
          { title: "냄비/프라이팬세트" },
          { title: "찜솥/들통" },
          { title: "압력솥/가마솥" },
        ],
      },
      {
        title: "주방조리도구",
        submenu: [
          { title: "조리도구" },
          { title: "조리도구세트" },
          { title: "가위/슬라이서스/스퀴져" },
          { title: "믹싱볼/대야" },
          { title: "채반/소쿠리" },
          { title: "다지기/절구/밀대" },
          { title: "석쇠/버너/화로" },
          { title: "야채탈수기" },
          { title: "간식/도시락조리도구" },
          { title: "베이킹용품" },
          { title: "칼" },
          { title: "도마" },
        ],
      },
      {
        title: "그릇/홈세트",
        submenu: [
          { title: "식기홈세트" },
          { title: "그릇/식기" },
          { title: "접시/플레이트" },
          { title: "식탁보/테이블매트" },
          { title: "쟁반/베드트레이" },
          { title: "이유/유아식기" },
          { title: "제기/제수용품" },
        ],
      },
      {
        title: "수저/커트러리",
        submenu: [
          { title: "수저/커트러리세트" },
          { title: "숟가락/티스푼" },
          { title: "젓가락" },
          { title: "포크/디저트포크" },
          { title: "나이프" },
          { title: "유아동수저" },
          { title: "서빙스푼/스쿱" },
          { title: "수저통/수저받침" },
        ],
      },
      {
        title: "컵/텀블러/와인용품",
        submenu: [
          { title: "머그/드링크차" },
          { title: "커피잔/찻잔" },
          { title: "텀블러/콜드컵" },
          { title: "유아동컵/빨대컵" },
          { title: "물컵/주스컵" },
          { title: "유리컵/맥주잔" },
          { title: "와인용품" },
          { title: "주류용품" },
          { title: "컵소품" },
        ],
      },
      {
        title: "주전자/커피/티용품",
        submenu: [
          { title: "주전자/티포트" },
          { title: "커피용품" },
          { title: "티용품" },
        ],
      },
      {
        title: "주방수납/정리",
        submenu: [
          { title: "공간별수납/정리" },
          { title: "식기건조대/선반" },
          { title: "주방정리소품" },
          { title: "교자상" },
        ],
      },
      {
        title: "밀페저장/도시락",
        submenu: [
          { title: "밀페보관용기" },
          { title: "특수저장용기" },
          { title: "양념통/오일병" },
          { title: "쌀통/잡곡통/항아리" },
          { title: "김치통/진공항아리" },
          { title: "물병/물통/텀블러" },
          { title: "도시락통/가방/찬합" },
          { title: "이유식조리보관" },
          { title: "유아동물병/도시락" },
        ],
      },
      {
        title: "주방잡화",
        submenu: [
          { title: "수세미/세척솔" },
          { title: "고무장갑" },
          { title: "행주" },
          { title: "앞치마/오븐장갑" },
          { title: "주방매트/다용도매트" },
          { title: "식탁보/테이블매트" },
          { title: "음식물쓰레기통" },
          { title: "싱크대용품" },
          { title: "아트보드/렌지가드" },
          { title: "계량/저울/타이머" },
          { title: "덮개/받침" },
          { title: "냅킨/주방수건" },
          { title: "오프너/병따개" },
          { title: "더보기" },
        ],
      },
      {
        title: "일회용품/종이컵",
        submenu: [
          { title: "랩/호일/유산지" },
          { title: "키친타올" },
          { title: "일회용장갑" },
          { title: "위생백/비닐봉투" },
          { title: "일회용컵" },
          { title: "일회용수저" },
          { title: "일회용용기/도시락" },
          { title: "배달일회용용품" },
          { title: "빨대/스트로우" },
          { title: "기타주방일회용품" },
        ],
      },
      {
        title: "보온/보냉용품",
        submenu: [
          { title: "보온/보냉병" },
          { title: "보온/보냉도시락" },
          { title: "보온죽통/푸드차" },
          { title: "보온/보냉텀블러" },
          { title: "보온/보냉주전자" },
          { title: "아이스박스/아이스백" },
          { title: "아이스물통/워터저그" },
          { title: "쿨러백/보온보냉소품" },
        ],
      },
      { title: "수입주방" },
      {
        title: "1인가구 주방용품",
        submenu: [
          { title: "1인 식기세트" },
          { title: "샐러드볼/시리얼볼" },
          { title: "미니밥솥" },
          { title: "냉동밥 보관용기" },
          { title: "홈바" },
          { title: "전자레인지" },
          { title: "전기레인지" },
          { title: "에어프라이어" },
          { title: "멀티포트/티포트" },
          { title: "핸드블렌더" },
          { title: "토스터" },
          { title: "냄비/프라이팬" },
          { title: "칼/가위/도마" },
          { title: "더보기" },
        ],
      },
    ],
  },
  {
    icon: "life",
    title: "생활용품",
    submenu: [
      {
        title: "방한용품",
        submenu: [
          { title: "손난로/핫팩" },
          { title: "보온/난방텐트" },
          { title: "단열에어캡/단열필름" },
          { title: "방풍비닐" },
          { title: "문풍지/틈막이" },
          { title: "폼블럭/단열벽지" },
          { title: "물기흡수 테이프" },
          { title: "방한커튼" },
          { title: "찜질용품" },
          { title: "좌훈용품" },
          { title: "아이마스크" },
        ],
      },
      {
        title: "헤어",
        submenu: [
          { title: "샴푸/린스" },
          { title: "트리트먼트/팩/앰플" },
          { title: "스타일링/케어/세트" },
          { title: "염색/파마" },
        ],
      },
      {
        title: "바디/세안",
        submenu: [
          { title: "샤워/입욕용품" },
          { title: "바디로션/크림" },
          { title: "핸드/풋/데오" },
          { title: "제모/슬리밍/청결제" },
          { title: "클렌징/필링" },
        ],
      },
      {
        title: "구강/면도",
        submenu: [
          { title: "면도기/날" },
          { title: "면도크림/젤" },
          { title: "치약" },
          { title: "칫솔" },
          { title: "전동칫솔/칫솔모" },
          { title: "치약/칫솔 세트" },
          { title: "구강청결제" },
          { title: "치실/치간칫솔" },
          { title: "치아미백제" },
          { title: "구강보조용품" },
        ],
      },
      {
        title: "화장지/물티슈",
        submenu: [
          { title: "화장지" },
          { title: "갑티슈/여행용티슈" },
          { title: "물티슈/비데티슈" },
          { title: "키친타올" },
        ],
      },
      {
        title: "생리대/성인기저귀",
        submenu: [
          { title: "일반생리대" },
          { title: "오버나이트" },
          { title: "팬티라이너" },
          { title: "체내형/생리컵" },
          { title: "면 생리대" },
          { title: "산모/임산부패드" },
          { title: "위생/생리팬티" },
          { title: "성인기저귀" },
          { title: "여성청결제" },
        ],
      },
      {
        title: "기저귀",
        submenu: [
          { title: "일회용기저귀" },
          { title: "수영장기저귀" },
          { title: "천기저귀/액세서리" },
          { title: "배변훈련팬티" },
          { title: "기저귀케익" },
          { title: "기저귀크림/파우더" },
          { title: "기저귀정리함" },
          { title: "기저귀매트" },
          { title: "기저귀통/봉투" },
          { title: "기저귀가방" },
        ],
      },
      {
        title: "세탁세제",
        submenu: [
          { title: "액체세제" },
          { title: "분말세제" },
          { title: "캡슐세제" },
          { title: "시트세제" },
          { title: "섬유유연제" },
          { title: "울세제/홈드라이세제" },
          { title: "향기지속제" },
          { title: "표백제" },
          { title: "세탁비누" },
          { title: "얼룩/찌든때 제거제" },
          { title: "운동화/가죽크리너" },
          { title: "유아세제/섬유유연제" },
          { title: "세제선물세트" },
        ],
      },
      {
        title: "청소/주방세제",
        submenu: [
          { title: "친환경/천연세제" },
          { title: "청소세제" },
          { title: "주방세제" },
          { title: "세제선물세트" },
        ],
      },
      {
        title: "탈취/방향/살충",
        submenu: [
          { title: "탈취제" },
          { title: "제습제" },
          { title: "방향제" },
          { title: "캔들/디퓨저" },
          { title: "살충제/벌레약" },
          { title: "야외활동케어" },
          { title: "방충용품" },
          { title: "곰팡이/진드기" },
        ],
      },
      {
        title: "건강/의료용품",
        submenu: [
          { title: "마스크" },
          { title: "의약외품/상비용품" },
          { title: "눈/렌즈용품" },
          { title: "코/수면용품" },
          { title: "자세교정/보호대" },
          { title: "마사지용품" },
          { title: "한방/찜질용품" },
          { title: "건강측정용품" },
          { title: "전문의료옹품" },
          { title: "건강액세서리" },
          { title: "활동보조용품" },
        ],
      },
      {
        title: "성인용품(19)",
        submenu: [
          { title: "콘돔" },
          { title: "러브젤" },
          { title: "성인 완구/게임(19)" },
          { title: "성인용품세트(19)" },
          { title: "성인 란제리(19)" },
          { title: "성인 코스튬(19)" },
          { title: "성인 가구(19)" },
          { title: "구속/처벌 용품(19)" },
          { title: "성인 도서/DVD(19)" },
          { title: "금연/흡연용품(19)" },
        ],
      },
      {
        title: "세탁/청소용품",
        submenu: [
          { title: "청소용품" },
          { title: "밀대/청소포" },
          { title: "빨래건조대" },
          { title: "빨래용품" },
          { title: "휴지통" },
          { title: "분리수거함" },
          { title: "먼지제거/클리너" },
          { title: "세탁/다림용품" },
        ],
      },
      {
        title: "욕실용품",
        submenu: [
          { title: "샤워기/헤드" },
          { title: "목욕/샤워용품" },
          { title: "수건/타월" },
          { title: "욕실수납/정리" },
          { title: "욕실화" },
          { title: "욕실매트/발판" },
          { title: "욕조" },
          { title: "세면대/세면기" },
          { title: "변기/비데용품" },
          { title: "욕실거울" },
          { title: "욕실용품/잡화" },
          { title: "유아욕실용품" },
          { title: "수전용품" },
          { title: "더보기" },
        ],
      },
      {
        title: "생활전기용품",
        submenu: [
          { title: "멀티탭/연장선" },
          { title: "전구/램프" },
          { title: "조명기구/부속" },
          { title: "전선정리용품" },
          { title: "전기설비/자재" },
          { title: "건전지/배터리" },
        ],
      },
      {
        title: "수납/정리",
        submenu: [
          { title: "선반/진열대" },
          { title: "리빙박스" },
          { title: "이사박스/종이박스" },
          { title: "수납장/서랍장" },
          { title: "바구니/칸막이" },
          { title: "행거" },
          { title: "옷걸이" },
          { title: "압축팩/커버" },
          { title: "슈즈렉/우산꽂이" },
          { title: "수납케이스" },
          { title: "욕실정리용품" },
          { title: "휴지통/분리수거함" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "interior",
    title: "홈인테리어",
    submenu: [
      {
        title: "크리스마스용품",
        submenu: [
          { title: "트리/트리장식" },
          { title: "크리스마스 조명" },
          { title: "크리스마스 장식" },
          { title: "캔들/워머" },
          { title: "디퓨저" },
        ],
      },
      {
        title: "방한용품",
        submenu: [
          { title: "손난로/핫팩" },
          { title: "보온/난방텐트" },
          { title: "단열에어캡/단열필름" },
          { title: "방풍비닐" },
          { title: "문풍지/틈막이" },
          { title: "폼블록/단열벽지" },
          { title: "물기흡수 테이프" },
          { title: "방한커튼" },
          { title: "찜질용품" },
          { title: "좌훈용품" },
          { title: "아이마스크" },
        ],
      },
      {
        title: "F/W 침구샵",
        submenu: [
          { title: "이불/침구세트" },
          { title: "매트리스/토퍼" },
          { title: "패드/스프레드" },
          { title: "침구커버" },
          { title: "난방텐트" },
          { title: "베개/바디필로우" },
          { title: "커튼/블라인드" },
          { title: "카페트/쿠션" },
          { title: "가전/가구 커버" },
          { title: "유아동침구" },
        ],
      },
      {
        title: "싱글하우스",
        submenu: [
          { title: "침대/매트리스" },
          { title: "침구" },
          { title: "러그/카페트/거실화" },
          { title: "커튼/블라인드" },
          { title: "책상/테이블" },
          { title: "의자/소파" },
          { title: "화장대" },
          { title: "조명/스탠드" },
          { title: "인테리어소품" },
          { title: "행거" },
          { title: "선반/수납장" },
          { title: "리빙박스/정리용품" },
        ],
      },
      {
        title: "홈데코",
        submenu: [
          { title: "캔들/캔들홀더" },
          { title: "디퓨저/방향제" },
          { title: "화병/화분" },
          { title: "조화/드라이플라워" },
          { title: "홈데코 소품" },
          { title: "시계" },
          { title: "거울" },
          { title: "액자" },
          { title: "그림/사진" },
          { title: "시트지/스티커" },
          { title: "조명/스탠드" },
          { title: "러그/카페트" },
          { title: "쿠션/방석" },
          { title: "더보기" },
        ],
      },
      {
        title: "가구",
        submenu: [
          { title: "침실가구" },
          { title: "드레스룸" },
          { title: "거실가수" },
          { title: "주방가구" },
          { title: "학생/사무용가구" },
          { title: "유아동가구" },
          { title: "야외가구" },
          { title: "수납가구" },
        ],
      },
      {
        title: "수납/정리",
        submenu: [
          { title: "행거" },
          { title: "옷걸이/도어훅" },
          { title: "리빙박스" },
          { title: "바구니/바스켓" },
          { title: "압축팩/커버" },
          { title: "선반/정리대" },
          { title: "기타정리용품" },
          { title: "휴지통" },
        ],
      },
      {
        title: "침구",
        submenu: [
          { title: "이불" },
          { title: "요/매트" },
          { title: "매트" },
          { title: "이불솜/속" },
          { title: "침구커버" },
          { title: "침구세트" },
          { title: "유아동침구" },
          { title: "베개" },
          { title: "롱쿠션/바디필로우" },
          { title: "담요" },
          { title: "죽부인" },
          { title: "쿨매트" },
          { title: "전기/온수매트" },
        ],
      },
      {
        title: "커튼/블라인드",
        submenu: [
          { title: "커튼" },
          { title: "블라인드/쉐이드" },
          { title: "롤스크린" },
          { title: "버티칼" },
          { title: "문발" },
          { title: "커튼부자재" },
          { title: "난방텐트" },
          { title: "모기장/캐노피" },
        ],
      },
      {
        title: "카페트/쿠션/거실화",
        submenu: [
          { title: "러그/카페트" },
          { title: "발매트/주방매트" },
          { title: "놀이/다용도매트" },
          { title: "원목/대자리" },
          { title: "쿠션/방석" },
          { title: "거실화" },
          { title: "소파패드/커버" },
          { title: "가전/가구커버" },
          { title: "홈패브릭" },
        ],
      },
      {
        title: "수예/수선",
        submenu: [
          { title: "원단" },
          { title: "실" },
          { title: "바늘" },
          { title: "반짇고리세트" },
          { title: "재봉틀 용품" },
          { title: "수선/재단도구" },
          { title: "단추/레이스" },
          { title: "장식/부자재" },
          { title: "솜/보충재" },
          { title: "뜨개질용품" },
          { title: "자수/십자수" },
          { title: "가죽공예" },
          { title: "퀄트" },
          { title: "더보기" },
        ],
      },
      {
        title: "욕실용품",
        submenu: [
          { title: "샤워기/헤드" },
          { title: "목욕/샤워용품" },
          { title: "수건/타월" },
          { title: "욕실수납/정리" },
          { title: "욕실화" },
          { title: "욕실매트/발판" },
          { title: "욕조" },
          { title: "세면대/세면기" },
          { title: "변기/비데용품" },
          { title: "욕실거울" },
          { title: "욕실용품/잡화" },
          { title: "유아욕실용품" },
          { title: "수전용품" },
          { title: "더보기" },
        ],
      },
      {
        title: "조명/스탠드",
        submenu: [
          { title: "장스탠드" },
          { title: "단스탠드" },
          { title: "무드등" },
          { title: "줄조명" },
          { title: "학생스탠드" },
          { title: "북라이트" },
          { title: "LED캔들" },
          { title: "천장등/벽등" },
          { title: "전구/형광등" },
          { title: "네온사인" },
          { title: "퍽라이트" },
        ],
      },
      {
        title: "셀프인테리어",
        submenu: [
          { title: "벽지/도배용품" },
          { title: "페인트/핸디코드" },
          { title: "장판/바닥재" },
          { title: "시트지/스티커" },
          { title: "폼블럭/타일/벽돌" },
          { title: "조명인테리어" },
          { title: "보수용품" },
          { title: "공구/자재" },
          { title: "인테리어소품" },
          { title: "인테리어도서" },
          { title: "건전기/멀티탭" },
        ],
      },
      {
        title: "원예/가드닝",
        submenu: [
          { title: "꽃다발/꽃선물" },
          { title: "다육이/선인장" },
          { title: "식물/나무" },
          { title: "조화/비누꽃" },
          { title: "드라이플라워" },
          { title: "화분/화병" },
          { title: "씨앗/텃밭세트" },
          { title: "숯화분/석부작" },
          { title: "흙/영양제/살충" },
          { title: "원예도구" },
          { title: "야외가구/소품" },
          { title: "잔디/농기구" },
        ],
      },
    ],
  },
  {
    icon: "digital",
    title: "가전디지털",
    submenu: [
      {
        title: "TV/영상가전",
        submenu: [
          { title: "TV" },
          { title: "미러링/스트리밍" },
          { title: "TV 액세서리" },
          { title: "블루레이/DVD/DivX" },
          { title: "빔/프로젝터/스크린" },
        ],
      },
      {
        title: "냉장고",
        submenu: [
          { title: "3/4도어냉장고" },
          { title: "양문형냉장고" },
          { title: "일반냉장고" },
          { title: "미니냉장고" },
          { title: "김치냉장고" },
          { title: "냉동고" },
          { title: "전용냉장고" },
        ],
      },
      {
        title: "세탁기/건조기",
        submenu: [
          { title: "세탁기건조기세트" },
          { title: "세탁기" },
          { title: "건조기" },
          { title: "의류관리기" },
          { title: "신발건조기" },
          { title: "탈수기" },
          { title: "액세서리" },
        ],
      },
      {
        title: "생활가전",
        submenu: [
          { title: "공기청정기" },
          { title: "다리미/재봉/보풀" },
          { title: "도어록/비디오폰" },
          { title: "비데/온수기" },
          { title: "전동칫솔/살균기" },
          { title: "학습용 스탠드" },
          { title: "전화기/무전기" },
        ],
      },
      {
        title: "청소기",
        submenu: [
          { title: "먼지비움청소기" },
          { title: "스틱청소기" },
          { title: "진공청소기" },
          { title: "로봇청소기" },
          { title: "물걸레청소기" },
          { title: "침구청소기" },
          { title: "핸디청소기" },
          { title: "스팀청소기" },
          { title: "차량용청소기" },
          { title: "업소용청소기" },
          { title: "필터/액세서리" },
        ],
      },
      {
        title: "계절가전",
        submenu: [
          { title: "공기청정기" },
          { title: "선풍기" },
          { title: "에어컨" },
          { title: "제습기" },
          { title: "서큘레이터" },
          { title: "냉풍기" },
          { title: "건조기/탈수기" },
          { title: "모기/해충 퇴치기" },
          { title: "가습기/에어워셔" },
          { title: "전기요/매트" },
          { title: "냉온수매트" },
          { title: "히터/온풍기" },
          { title: "손난로/발난로" },
        ],
      },
      {
        title: "뷰티/헤어가전",
        submenu: [
          { title: "헤어드라이어" },
          { title: "고데기/매직기" },
          { title: "헤어스타일러" },
          { title: "두피/헤어관리" },
          { title: "피부관리기기" },
          { title: "면도기/이발기" },
          { title: "제모기" },
          { title: "눈썹/네일관리" },
        ],
      },
      {
        title: "건강가전",
        submenu: [
          { title: "안마의자" },
          { title: "안마/찜질기" },
          { title: "전동칫솔/구강가전" },
          { title: "비데" },
          { title: "건강측정/의료기" },
          { title: "살균/소독기" },
          { title: "손건조기/소독기" },
        ],
      },
      {
        title: "주방가전",
        submenu: [
          { title: "전기밥솥" },
          { title: "전자레인지" },
          { title: "오븐" },
          { title: "가스레인지" },
          { title: "전기레인지" },
          { title: "식기세척/건조기" },
          { title: "믹서기/블렌더" },
          { title: "커피메이커/머신" },
          { title: "빙수기/제빙기" },
          { title: "전기포트" },
          { title: "에어프라이어" },
          { title: "튀김기" },
          { title: "토스터" },
          { title: "더보기" },
        ],
      },
      { title: "노트북" },
      {
        title: "데스크탑",
        submenu: [
          { title: "브랜드PC" },
          { title: "일체형PC" },
          { title: "조립PC" },
          { title: "미니PC" },
        ],
      },
      { title: "모니터" },
      { title: "휴대폰" },
      {
        title: "태블릿PC",
        submenu: [{ title: "태블릿/PC" }, { title: "액세서리" }],
      },
      {
        title: "스마트워치/밴드",
        submenu: [
          { title: "스마트워치" },
          { title: "스마트밴드" },
          { title: "액세서리" },
        ],
      },
      {
        title: "게임",
        submenu: [
          { title: "게이밍노트북" },
          { title: "게이밍데스크탑" },
          { title: "게이밍모니터" },
          { title: "마우스/키보드/헤드셋" },
          { title: "그래픽카드/메인보드" },
          { title: "PC타이틀/주변기기" },
          { title: "플레이스테이션" },
          { title: "닌텐도" },
          { title: "XBOX" },
          { title: "레트로/기타게임" },
          { title: "휴대폰게임" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "sports",
    title: "스포츠/레저",
    submenu: [
      {
        title: "캠핑전문관",
        submenu: [
          { title: "백패킹" },
          { title: "미니멀캠핑" },
          { title: "오토캠핑" },
          { title: "먹거리" },
          { title: "텐트" },
          { title: "타프/그늘막" },
          { title: "텐트/타프 부품" },
          { title: "의자/테이블" },
          { title: "침낭/매트/해먹" },
          { title: "캠핑주방용품" },
          { title: "수납/정리소품" },
          { title: "랜턴/조명" },
          { title: "캠핑공구" },
          { title: "더보기" },
        ],
      },
      {
        title: "홈트레이닝",
        submenu: [
          { title: "스트레칭/마사지" },
          { title: "유산소" },
          { title: "근력" },
          { title: "보호대/체중계" },
        ],
      },
      {
        title: "수영/수상스포츠",
        submenu: [
          { title: "실내 수영복" },
          { title: "비치웨어/래쉬가드" },
          { title: "수영용품" },
          { title: "물놀이용품" },
          { title: "아쿠아슈즈" },
          { title: "스노클링/다이빙" },
          { title: "서핑/수상스키" },
          { title: "고무보트/카누" },
        ],
      },
      {
        title: "골프",
        submenu: [
          { title: "골프클럽" },
          { title: "골프백" },
          { title: "피팅/관리용품" },
          { title: "골프웨어" },
          { title: "골프장갑/잡화" },
          { title: "골프화" },
          { title: "골프공" },
          { title: "필드용품" },
          { title: "연습용품" },
        ],
      },
      {
        title: "자전거",
        submenu: [
          { title: "자전거" },
          { title: "보호장비" },
          { title: "자전거 액세서리" },
          { title: "자전거부품" },
          { title: "자전거의류" },
          { title: "자전거장갑/잡화" },
          { title: "자전거가방/수납" },
          { title: "자전거신발" },
          { title: "정비용품" },
          { title: "거치대/트레이너" },
        ],
      },
      {
        title: "킥보드/스케이트",
        submenu: [
          { title: "킥보드/트라이더" },
          { title: "전동휠/보드" },
          { title: "스케이트보드" },
          { title: "인라인스케이트" },
          { title: "보호장비" },
        ],
      },
      {
        title: "낚시",
        submenu: [
          { title: "바다낚시" },
          { title: "민물낚시" },
          { title: "낚시대" },
          { title: "낚시릴" },
          { title: "줄/바늘/채비" },
          { title: "미끼/떡밥/루어" },
          { title: "낚시 가방/잡화" },
          { title: "낚시복/장화" },
          { title: "낚시장비/그물" },
          { title: "낚시공구/소품" },
          { title: "좌대/야외용품" },
        ],
      },
      {
        title: "등산/아웃도어",
        submenu: [
          { title: "남성등산의류" },
          { title: "여성등산의류" },
          { title: "유아동등산의류" },
          { title: "등산배낭/소품" },
          { title: "등산스틱" },
          { title: "등산화/아이젠" },
          { title: "등산모자/잡화" },
          { title: "등산용품/랜턴" },
          { title: "나침반/망원경" },
          { title: "암벽/등반 장비" },
          { title: "빙벽/겨울용품" },
        ],
      },
      {
        title: "스포츠신발",
        submenu: [
          { title: "런닝화/운동화" },
          { title: "샌들/슬리퍼" },
          { title: "아쿠아슈즈" },
          { title: "등산화" },
          { title: "골프화" },
          { title: "축구화" },
          { title: "야구화" },
          { title: "농구화" },
          { title: "배구화" },
          { title: "족구화" },
          { title: "볼링화" },
          { title: "배드민턴화" },
          { title: "테니스화" },
          { title: "더보기" },
        ],
      },
      {
        title: "남성스포츠의류",
        submenu: [
          { title: "속옷/언더레이어" },
          { title: "스포츠 티셔츠" },
          { title: "스포츠 자켓/집업" },
          { title: "스포츠 바지/하의" },
          { title: "상하의 세트" },
          { title: "골프의류" },
          { title: "등산의류" },
          { title: "자전거의류" },
          { title: "수영복/래쉬가드" },
          { title: "스키/보드복" },
          { title: "축구복" },
          { title: "야구복" },
          { title: "배드민턴복" },
          { title: "더보기" },
        ],
      },
      {
        title: "여성스포츠의류",
        submenu: [
          { title: "속옷/언더레이어" },
          { title: "스포츠 티셔츠" },
          { title: "스포츠 자켓/집업" },
          { title: "스포츠 바지/하의" },
          { title: "상하의 세트" },
          { title: "요가복" },
          { title: "골프의류" },
          { title: "등산의류" },
          { title: "자전거의류" },
          { title: "수영복/래쉬가드" },
          { title: "스키/보드복" },
          { title: "발레복" },
          { title: "배드민턴" },
          { title: "더보기" },
        ],
      },
      {
        title: "유아스포츠의류",
        submenu: [
          { title: "스포츠 티셔츠" },
          { title: "스포츠 자켓/집업" },
          { title: "스포츠 바지/하의" },
          { title: "상하의 세트" },
          { title: "골프의류" },
          { title: "등산의류" },
          { title: "수영복/래쉬가드" },
          { title: "스키/보드복" },
          { title: "축구복" },
          { title: "야구복" },
          { title: "발레복" },
          { title: "기타 유니폼" },
        ],
      },
      {
        title: "스포츠잡화",
        submenu: [
          { title: "가방/파우치" },
          { title: "모자" },
          { title: "고글/선글라스" },
          { title: "장갑" },
          { title: "양말/타이즈" },
          { title: "팔토시/워머" },
          { title: "스카프/넥워머" },
          { title: "보호대/아대" },
          { title: "시계" },
          { title: "벨트" },
          { title: "안전밴드" },
          { title: "액세서리 기타" },
        ],
      },
      {
        title: "구기스포츠",
        submenu: [
          { title: "축구" },
          { title: "야구" },
          { title: "농구" },
          { title: "배구/피구/족구" },
          { title: "볼링" },
          { title: "당구/포켓볼" },
          { title: "기타 구기스포츠" },
          { title: "훈련/연습용품" },
          { title: "심판의류/용폼" },
        ],
      },
      {
        title: "라켓스포츠",
        submenu: [
          { title: "배드민턴" },
          { title: "테니스" },
          { title: "스쿼시" },
          { title: "탁구" },
          { title: "기타 라켓스포츠" },
          { title: "훈련/연습용품" },
          { title: "심판의류/용품" },
        ],
      },
      {
        title: "헬스/요가/댄스",
        submenu: [
          { title: "요가/필라테스" },
          { title: "요가복" },
          { title: "근력운동" },
          { title: "유산소운동" },
          { title: "스트레칭/균형" },
          { title: "댄스/에어로빅" },
          { title: "헬스소품/보호대" },
          { title: "운동측정용품" },
          { title: "부위별 운동용품" },
          { title: "헬스보충식품" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "car",
    title: "자동차용품",
    submenu: [
      {
        title: "인테리어",
        submenu: [
          { title: "방향제/공기청정" },
          { title: "바닥매트/트렁크매트" },
          { title: "시트/쿠션" },
          { title: "차박매트" },
          { title: "핸들용품" },
          { title: "커버/몰딩" },
          { title: "수납/정리용품" },
          { title: "편의용품/액세서리" },
          { title: "햇빛가리개/썬팅" },
        ],
      },
      {
        title: "익스테리어",
        submenu: [
          { title: "스티커/앰블럼" },
          { title: "문콕방지/몰딩" },
          { title: "썬바이저" },
          { title: "번호판스티커/프레임" },
          { title: "안테나/볼" },
          { title: "루프/캐리어용품" },
          { title: "미러용품" },
          { title: "주유구캡/혼유방지링" },
        ],
      },
      {
        title: "세차/카케어",
        submenu: [
          { title: "세차용품세트" },
          { title: "카샴푸/세정제" },
          { title: "타월/스펀지" },
          { title: "세차호스/거품분사기" },
          { title: "세차박스/스텝박스" },
          { title: "물왁스/퀵디테일러" },
          { title: "차량용청소기" },
          { title: "먼지털이개" },
          { title: "유리발수코팅제" },
          { title: "실내세정제" },
          { title: "흠집제거/복원" },
          { title: "광택" },
          { title: "바디커버" },
          { title: "더보기" },
        ],
      },
      {
        title: "차량용 전자기기",
        submenu: [
          { title: "HUD/계기판" },
          { title: "무선충전 거치대" },
          { title: "일반거치대" },
          { title: "차량용충전기" },
          { title: "멀티소켓" },
          { title: "블랙박스" },
          { title: "하이패스" },
          { title: "내비게이션" },
          { title: "후방카메라/감지기" },
          { title: "음향기기/AV" },
          { title: "차량용가전" },
        ],
      },
      {
        title: "차량관리/소모품",
        submenu: [
          { title: "와이퍼" },
          { title: "워셔액" },
          { title: "에어컨필터" },
          { title: "엔진오일" },
          { title: "첨가제" },
          { title: "냉각수/부동액" },
          { title: "요소수" },
          { title: "초순수/정제수" },
          { title: "기타 오일/필터" },
          { title: "점프스타터" },
          { title: "배터리용품" },
          { title: "타이어/휠" },
          { title: "스노우체인" },
          { title: "더보기" },
        ],
      },
      {
        title: "RV/아웃도어",
        submenu: [
          { title: "캠핑용품" },
          { title: "차박매트" },
          { title: "인버터/멀티소켓" },
          { title: "루프/캐리어용품" },
        ],
      },
      {
        title: "부품/안전/공구",
        submenu: [
          { title: "정전기방지용품" },
          { title: "안전삼각대/소화기" },
          { title: "방음재" },
          { title: "차량용리프트" },
          { title: "고인목/버팀목" },
          { title: "카본/레자시트지" },
          { title: "차량용접착제/테이프" },
          { title: "기타공구장비" },
          { title: "부품/튜닝용품" },
          { title: "전기용품" },
        ],
      },
      {
        title: "오토바이/전동킥보드",
        submenu: [
          { title: "오토바이/스쿠터" },
          { title: "헬멧/고글" },
          { title: "오토바이의류" },
          { title: "오토바이장갑" },
          { title: "오토바이부츠/잡화" },
          { title: "오토바이보호장비" },
          { title: "배달가방/탑박스" },
          { title: "오토바이액세서리" },
          { title: "오토바이부품/튜닝/정비" },
          { title: "오토바이전자기기" },
          { title: "전동킥보드/스쿠터용품" },
        ],
      },
      { title: "로켓설치 타이어" },
    ],
  },
  {
    icon: "book",
    title: "도서/음반/DVD",
    submenu: [
      {
        title: "유아/어린이",
        submenu: [
          { title: "그림책" },
          { title: "어린이 문학" },
          { title: "초점책/영아책" },
          { title: "놀이책/토이북" },
          { title: "학습/교양" },
          { title: "만화/애니메이션" },
          { title: "전집/세트" },
          { title: "어린이 잡지" },
          { title: "유아동 해외도서" },
          { title: "음반/DVD" },
          { title: "누리과정 주제" },
          { title: "교과서수록도서" },
          { title: "STEAM도서" },
          { title: "더보기" },
        ],
      },
      {
        title: "소설/에세이/시",
        submenu: [
          { title: "소설" },
          { title: "장르소설" },
          { title: "테마소설" },
          { title: "고전문학/신화" },
          { title: "문학전집" },
          { title: "에세이" },
          { title: "시" },
          { title: "희곡/시나리오" },
          { title: "문학잡지" },
        ],
      },
      {
        title: "초중고참고서",
        submenu: [
          { title: "초등학생" },
          { title: "중학생" },
          { title: "고등학생" },
        ],
      },
      {
        title: "가정 살림",
        submenu: [
          { title: "요리" },
          { title: "임신/출산/태교" },
          { title: "결혼/가족" },
          { title: "육아/교육" },
          { title: "자녀 학습/학교" },
          { title: "살림/정리수납" },
          { title: "집/인테리어" },
          { title: "원예/조경/텃밭" },
        ],
      },
      {
        title: "건강 취미",
        submenu: [
          { title: "다이터트/미용" },
          { title: "요가/체조/기타" },
          { title: "스포츠/오락" },
          { title: "등산/낚시/바둑" },
          { title: "건강정보" },
          { title: "의학/약학" },
          { title: "질병과 치료법" },
          { title: "한의학/한방치료" },
          { title: "컬러링북" },
          { title: "공예/DIY" },
          { title: "원예" },
          { title: "패션/뷰티" },
          { title: "퍼즐/스도쿠" },
          { title: "더보기" },
        ],
      },
      {
        title: "경제 경영",
        submenu: [
          { title: "경제" },
          { title: "경영" },
          { title: "마케팅/세일즈" },
          { title: "투자/재테크" },
          { title: "인터넷비즈니스" },
          { title: "창업/취업/은퇴" },
          { title: "성공스토리" },
          { title: "경제/시사잡지" },
          { title: "총람/간행물" },
        ],
      },
      {
        title: "과학/공학",
        submenu: [
          { title: "기초과학/교양과학" },
          { title: "과학자" },
          { title: "뇌과학" },
          { title: "의학/법의학" },
          { title: "생명과학" },
          { title: "화학" },
          { title: "수학" },
          { title: "물리" },
          { title: "지구과학" },
          { title: "천문학" },
          { title: "인체" },
          { title: "공학" },
          { title: "농/축/수산학" },
          { title: "더보기" },
        ],
      },
      {
        title: "국어/외국어/사전",
        submenu: [
          { title: "국어" },
          { title: "한자" },
          { title: "영어" },
          { title: "영어시험대비" },
          { title: "일본어" },
          { title: "중국어" },
          { title: "중동/아랍어" },
          { title: "독일어" },
          { title: "프랑스어" },
          { title: "이탈리아어" },
          { title: "스페인어" },
          { title: "러시아어" },
          { title: "기타 동양어" },
          { title: "더보기" },
        ],
      },
      {
        title: "대학죠재",
        submenu: [
          { title: "인문학 계열" },
          { title: "어문학 계열" },
          { title: "자연과학 계열" },
          { title: "의약학/간호 계열" },
          { title: "사범대 계열" },
          { title: "농축산학 계열" },
          { title: "경상계열" },
          { title: "예체능/문화/기타 계열" },
          { title: "사회과학 계열" },
          { title: "법학계열" },
          { title: "공학계열" },
        ],
      },
      {
        title: "만화/라이트노벨",
        submenu: [
          { title: "만화 비평/작법" },
          { title: "애니메이션" },
          { title: "예술만화/교양만화" },
          { title: "시사/풍자만화" },
          { title: "취미/직업만화" },
          { title: "역사만화" },
          { title: "코믹/명랑만화" },
          { title: "스포츠만화" },
          { title: "소년만화" },
          { title: "장르만화" },
          { title: "드라마만화" },
          { title: "성인만화" },
          { title: "순정만화" },
          { title: "더보기" },
        ],
      },
      {
        title: "사회 정치",
        submenu: [
          { title: "생태/환경" },
          { title: "사회학" },
          { title: "사회비평/비판" },
          { title: "정치/외교" },
          { title: "북한/통일" },
          { title: "행정" },
          { title: "국방/군사" },
          { title: "법과 생활" },
          { title: "여성/젠더" },
          { title: "언론/미디어" },
          { title: "교육" },
          { title: "사회단체/NGO" },
          { title: "지리학/지정학" },
          { title: "더보기" },
        ],
      },
      {
        title: "수험서/자격증",
        submenu: [
          { title: "공무원 준비관" },
          { title: "교원임용시험" },
          { title: "한국사능력검정시험" },
          { title: "한국어능력검정시험" },
          { title: "한자시험" },
          { title: "취업/상식/적성" },
          { title: "경제/금융/회계" },
          { title: "공인중개/주택관리" },
          { title: "법/인문/사회/고시" },
          { title: "보건/위생/의학" },
          { title: "한국산업인력공단" },
          { title: "편입/검정고시/독학사" },
          { title: "LEET법학적성시험" },
          { title: "더보기" },
        ],
      },
      {
        title: "여행",
        submenu: [
          { title: "해외여행" },
          { title: "국내여행" },
          { title: "테마여행" },
          { title: "지도/지리" },
          { title: "여행회화" },
          { title: "워킹 홀리데이" },
          { title: "유학/해외연수/이민" },
          { title: "여행 에세이" },
        ],
      },
      {
        title: "역사",
        submenu: [
          { title: "한국사 일반" },
          { title: "한국고대/고려사" },
          { title: "조선사" },
          { title: "한국근현대사" },
          { title: "한국문화" },
          { title: "북한사" },
          { title: "일본사" },
          { title: "중국사" },
          { title: "아시아사" },
          { title: "서양사" },
          { title: "유럽사" },
          { title: "아메리카사/기타" },
          { title: "아프리카/오세아니아사" },
          { title: "더보기" },
        ],
      },
      {
        title: "예술",
        submenu: [
          { title: "건축" },
          { title: "미술" },
          { title: "음악" },
          { title: "사진" },
          { title: "무용" },
          { title: "연극/공연" },
          { title: "영화/비디오" },
          { title: "대중음악" },
          { title: "예술/대중문화 이해" },
          { title: "TV/라디오" },
          { title: "예술치료" },
          { title: "예술기행" },
          { title: "연예인 화보집" },
        ],
      },
      {
        title: "인문",
        submenu: [
          { title: "인문 일반" },
          { title: "철학/사상 일반" },
          { title: "심리학/심리일반" },
          { title: "기호학/언어학" },
          { title: "종교학/신화학" },
          { title: "한국철학" },
          { title: "동양철학" },
          { title: "서양철학" },
          { title: "논리학" },
          { title: "윤리학" },
          { title: "비평/창작/이론" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "hobby",
    title: "완구/취미",
    submenu: [
      {
        title: "캐릭터별완구",
        submenu: [
          { title: "뽀로로" },
          { title: "타요" },
          { title: "로보카폴리" },
          { title: "신비아파트" },
          { title: "콩순이" },
          { title: "시크릿쥬쥬" },
          { title: "헬로카봇" },
          { title: "빠샤메카드" },
          { title: "요괴메카드" },
          { title: "베이블레이드" },
          { title: "실바니안패밀리" },
          { title: "미미" },
          { title: "바비" },
          { title: "더보기" },
        ],
      },
      {
        title: "신생아/영아완구",
        submenu: [
          { title: "모빌" },
          { title: "초점책/헝겊책" },
          { title: "딸랑이" },
          { title: "치발기/케이스" },
          { title: "오뚝이" },
          { title: "멜로디/러닝완구" },
          { title: "목욕놀이완구" },
          { title: "애착/수면인형" },
          { title: "아기공" },
          { title: "아기체육관/러닝홈" },
          { title: "바운서" },
          { title: "쏘서/점퍼루/보행기" },
          { title: "걸음마보조기" },
          { title: "더보기" },
        ],
      },
      {
        title: "로봇/작동완구",
        submenu: [
          { title: "로봇" },
          { title: "베이블레이드/배틀팽이" },
          { title: "교통수단" },
          { title: "동물" },
          { title: "장난감총/칼" },
          { title: "작동완구" },
          { title: "어린이RC완구" },
          { title: "풀백장난감" },
          { title: "태엽장난감" },
        ],
      },
      {
        title: "역할놀이",
        submenu: [
          { title: "주방놀이" },
          { title: "소꿉놀이" },
          { title: "공구놀이" },
          { title: "마트/계산대놀이" },
          { title: "화장/꾸미기놀이" },
          { title: "아기돌보기놀이" },
          { title: "병원놀이" },
          { title: "청소놀이" },
          { title: "만들깉외" },
          { title: "악기놀이" },
          { title: "모래놀이" },
          { title: "낚시놀이" },
          { title: "장난감총/칼" },
          { title: "더보기" },
        ],
      },
      {
        title: "블록놀이",
        submenu: [
          { title: "레고" },
          { title: "옥스포드" },
          { title: "나노블록" },
          { title: "플레이모빌" },
          { title: "사각/십자블록" },
          { title: "원목블록" },
          { title: "자석블록" },
          { title: "소프트블록" },
          { title: "벽돌블록/빅블록" },
          { title: "기어블록" },
          { title: "마블런/레일블록" },
          { title: "나사조립블록" },
          { title: "도미노" },
        ],
      },
      {
        title: "인형",
        submenu: [
          { title: "봉제인형" },
          { title: "작동동물인형" },
          { title: "마론인형/옷" },
          { title: "인형집" },
          { title: "아기인형/유모차" },
          { title: "종이인형/코디북" },
          { title: "구체관절인형" },
          { title: "손가락인형" },
          { title: "마리오네트" },
          { title: "전통인형" },
          { title: "목각인형" },
        ],
      },
      {
        title: "물놀이/계절완구",
        submenu: [
          { title: "튜브" },
          { title: "비치볼" },
          { title: "풀장/수영장" },
          { title: "착용형 보조용품" },
          { title: "암링" },
          { title: "물놀이보트" },
          { title: "에어펌프" },
          { title: "킥판/킥보드" },
          { title: "스노클링/다이빙" },
          { title: "오리발/물갈퀴" },
          { title: "물총" },
          { title: "모래놀이" },
          { title: "목욕놀이" },
          { title: "더보기" },
        ],
      },
      {
        title: "승용완구",
        submenu: [
          { title: "자전거" },
          { title: "전동차/전동휠" },
          { title: "킥보드/트라이더" },
          { title: "전동휠/보드" },
          { title: "스카이콩콩" },
          { title: "인라인/롤러스케이트" },
          { title: "스케이트보드" },
          { title: "웨건/트레일러" },
          { title: "붕붕카" },
          { title: "지붕차" },
          { title: "실내승용완구" },
          { title: "헬멧/보호대" },
        ],
      },
      {
        title: "스포츠/야외완구",
        submenu: [
          { title: "구기종목" },
          { title: "양궁/사격/다트" },
          { title: "유아동장난감총" },
          { title: "비누방울/버블건" },
          { title: "물총" },
          { title: "모래놀이" },
          { title: "자전거/승용완구" },
          { title: "트램펄린" },
          { title: "훌라후프/줄넘기" },
          { title: "펀치백" },
          { title: "점핑볼" },
          { title: "캐치볼/원반던지기" },
          { title: "요요/액세서리" },
          { title: "더보기" },
        ],
      },
      {
        title: "실내대형완구",
        submenu: [
          { title: "다기능놀이터" },
          { title: "미끄럼틀" },
          { title: "그네/그네봉" },
          { title: "시소" },
          { title: "볼풀/볼텐트" },
          { title: "볼풀공" },
          { title: "놀이터널" },
          { title: "놀이집/놀이텐트" },
          { title: "트램펄린" },
          { title: "베이비룸" },
        ],
      },
      {
        title: "STEAM완구",
        submenu: [
          { title: "과학(S)" },
          { title: "기술(T)" },
          { title: "공학(E)" },
          { title: "예술(A)" },
          { title: "수학(M)" },
        ],
      },
      {
        title: "학습완구/교구",
        submenu: [
          { title: "과학/자연학습" },
          { title: "기술/공학완구" },
          { title: "미술/점토" },
          { title: "음악/악기놀이" },
          { title: "수학/도형완구" },
          { title: "언어학습완구" },
          { title: "학습카드" },
          { title: "학습벽보" },
          { title: "원목교구/가배" },
          { title: "퍼즐" },
          { title: "디지털학습완구" },
          { title: "교육용 보드게임" },
          { title: "자석/학습보드" },
        ],
      },
      {
        title: "보드게임",
        submenu: [
          { title: "멘사추천/학습게임" },
          { title: "두뇌게임" },
          { title: "균형/순발력게임" },
          { title: "추리/전략게임" },
          { title: "복불복/룰렛게임" },
          { title: "캐릭터/마술/타로카드" },
          { title: "스포츠/액션게임" },
          { title: "바둑/체스/윷놀이" },
          { title: "화투/트럼프/마작" },
          { title: "기타보드게임" },
          { title: "보드게임액세서리" },
        ],
      },
      {
        title: "RC완구/부품",
        submenu: [
          { title: "RC드론/쿼드콥터" },
          { title: "RC카" },
          { title: "RC헬기/비행기" },
          { title: "RC보트/잠수함" },
          { title: "RC탱크" },
          { title: "RC바이크/오토바이" },
          { title: "RC로봇" },
          { title: "RC부품/액세서리" },
          { title: "어린이RC완구" },
        ],
      },
      {
        title: "퍼즐/큐브/피젯토이",
        submenu: [
          { title: "직소퍼즐" },
          { title: "구슬퍼즐" },
          { title: "입체퍼즐" },
          { title: "유아동퍼즐" },
          { title: "캐스트/유레카퍼즐" },
          { title: "IQ퍼즐/스도쿠" },
          { title: "퍼즐액세서리" },
          { title: "큐브" },
          { title: "피젯토이" },
        ],
      },
      {
        title: "프라모델",
        submenu: [
          { title: "건담" },
          { title: "탱크/지프/밀리터리" },
          { title: "자동차/트럭/기차" },
          { title: "비행기/전투기/헬기" },
          { title: "배/전함/잠수함" },
          { title: "건물/빌딩/성" },
          { title: "로봇/우주선" },
          { title: "캐릭터/애니메이션" },
          { title: "공룡/동물" },
          { title: "4WD미니카" },
          { title: "디오라마재료" },
          { title: "도료/공구/기타" },
          { title: "서바이벌건/BB탄총" },
          { title: "더보기" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "office",
    title: "문구/오피스",
    submenu: [
      {
        title: "사무용품 전문관",
        submenu: [
          { title: "사무용문구" },
          { title: "파일/바인더" },
          { title: "사무용지/복사지" },
          { title: "데스크정리소품" },
          { title: "보드/칠판/광고" },
          { title: "봉투/포장용품" },
          { title: "디지털/사무기기" },
          { title: "사무용가구/수납" },
        ],
      },
      {
        title: "미술/화방용품",
        submenu: [
          { title: "수채화" },
          { title: "유화" },
          { title: "아크릴화" },
          { title: "디자인/구성" },
          { title: "동양화/서예" },
          { title: "조소/도예/판화" },
          { title: "지류/스케치북" },
          { title: "캔버스/판넬" },
          { title: "드로잉/채색도구" },
          { title: "봇" },
          { title: "파스텔/콩테/목탄" },
          { title: "캘리그라피" },
          { title: "애니메이션/만화" },
          { title: "더보기" },
        ],
      },
      {
        title: "캐릭터 문구",
        submenu: [
          { title: "카카오프렌즈" },
          { title: "핑크퐁" },
          { title: "뽀로로" },
          { title: "리락쿠마" },
          { title: "엉덩이탐정" },
          { title: "디즈니" },
          { title: "포켓몬스터" },
          { title: "짱구는 못말려" },
          { title: "헬로키티" },
          { title: "BT21" },
          { title: "마블/DC" },
          { title: "에비츄" },
          { title: "빨강머리 앤" },
          { title: "더보기" },
        ],
      },
      {
        title: "학용품/수업준비",
        submenu: [
          { title: "필기용품" },
          { title: "노트" },
          { title: "메모지/수첩" },
          { title: "학용품세트" },
          { title: "파일" },
          { title: "네임스티커/명찰" },
          { title: "지구본/지도" },
          { title: "과학시간" },
          { title: "수학시간" },
          { title: "미술시간" },
          { title: "음악시간" },
          { title: "체육시간" },
          { title: "학년별 준비물" },
          { title: "더보기" },
        ],
      },
      {
        title: "필기류",
        submenu: [
          { title: "펜/리필심" },
          { title: "연필" },
          { title: "샤프" },
          { title: "만년필" },
          { title: "형광펜" },
          { title: "사인펜/매직" },
          { title: "색연필" },
          { title: "붓펜/캘리그라피펜" },
          { title: "분필/보드마카" },
          { title: "지우개/수정액" },
          { title: "필통/파우치" },
        ],
      },
      {
        title: "노트/메모지",
        submenu: [
          { title: "유선/무선노트" },
          { title: "학습/과목노트" },
          { title: "초등학생노트" },
          { title: "노트커버/패드" },
          { title: "수첩" },
          { title: "가계부/캐쉬북" },
          { title: "일기장" },
          { title: "기록노트" },
          { title: "메모패드/리갈패드" },
          { title: "메모지/체크리스트" },
          { title: "점착메모지/포스트잇" },
          { title: "인덱스/플래그" },
        ],
      },
      {
        title: "다이어리/플래너",
        submenu: [
          { title: "다이어리" },
          { title: "다이어리소품" },
          { title: "스케쥴러" },
          { title: "캘린더" },
          { title: "프로젝트플래너" },
        ],
      },
      {
        title: "바인더/파일",
        submenu: [
          { title: "바인더" },
          { title: "파일" },
          { title: "클립보드/결재판" },
        ],
      },
      {
        title: "파티/이벤트",
        submenu: [
          { title: "테이블웨어" },
          { title: "초/티라이트" },
          { title: "풍선" },
          { title: "파티모자/머리띠" },
          { title: "파티장식/가랜드" },
          { title: "홈파티세트" },
          { title: "꽃잎/폭죽/불꽃놀이" },
          { title: "가발/가면/안경" },
          { title: "의상/분장용품" },
          { title: "응원/페스티벌" },
          { title: "마술용품" },
          { title: "기타파티소품" },
        ],
      },
      {
        title: "데코/포장용품",
        submenu: [
          { title: "선물/포장용품" },
          { title: "스티커" },
          { title: "스탬프/씰링" },
          { title: "모양펀치" },
          { title: "데코테이프" },
        ],
      },
      {
        title: "카드/엽서/봉투",
        submenu: [
          { title: "카드" },
          { title: "엽서" },
          { title: "편지지" },
          { title: "봉투" },
        ],
      },
      {
        title: "앨범",
        submenu: [
          { title: "일반포토앨범" },
          { title: "폴라로이드앨범" },
          { title: "티켓/영화앨범" },
          { title: "출산/성장앨범" },
          { title: "기타스크랩북" },
        ],
      },
      {
        title: "복사용품/라벨지",
        submenu: [
          { title: "복사용지" },
          { title: "출력라벨지" },
          { title: "전용지" },
          { title: "잉크/토너" },
        ],
      },
      {
        title: "보드/칠판/광고",
        submenu: [
          { title: "화이트보드/게시판" },
          { title: "블랙/칼라보드/게시판" },
          { title: "칠판보드/게시판" },
          { title: "콜크보드/게시판" },
          { title: "융보드/게시판" },
          { title: "메모보드" },
          { title: "타공판/메쉬보드" },
          { title: "보드/게시판소품" },
          { title: "메뉴판" },
          { title: "쇼카드" },
          { title: "아크릴꽂이/집게" },
          { title: "아크릴사인/표지판" },
          { title: "마네킹" },
          { title: "더보기" },
        ],
      },
    ],
  },
  {
    icon: "pet",
    title: "반려동물용품",
    submenu: [
      {
        title: "강아지 사료",
        submenu: [
          { title: "건식사료" },
          { title: "소프트사료" },
          { title: "습식사료" },
          { title: "건조/생식사료" },
          { title: "회식사료" },
          { title: "분유" },
          { title: "기능성사료" },
        ],
      },
      {
        title: "강아지 간식",
        submenu: [
          { title: "캔/파우치" },
          { title: "덴탈껌" },
          { title: "건조간식/육포" },
          { title: "동결건조간식" },
          { title: "비스켓/시리얼/쿠키" },
          { title: "캔디/젤리" },
          { title: "빵/케이크" },
          { title: "테린/회식" },
          { title: "져키/트릿" },
          { title: "음료" },
        ],
      },
      {
        title: "강아지 영양제",
        submenu: [{ title: "영양제" }, { title: "건강보조제" }],
      },
      {
        title: "강아지 용품",
        submenu: [
          { title: "하우스/울타리" },
          { title: "급식기/급수기" },
          { title: "의류/패션" },
          { title: "배변용품" },
          { title: "미용/목욕" },
          { title: "장난감/훈련용품" },
          { title: "펫캠/가전용품" },
          { title: "이동장/외출용품" },
          { title: "건강 관리" },
          { title: "강아지도서" },
        ],
      },
      {
        title: "고영이 사료",
        submenu: [
          { title: "건식사료" },
          { title: "습식/소프트사료" },
          { title: "건조생식사료" },
          { title: "회식사료" },
          { title: "분유" },
          { title: "기능성사료" },
        ],
      },
      {
        title: "고양이 간식",
        submenu: [
          { title: "캔" },
          { title: "파우치" },
          { title: "동결/건조간식" },
          { title: "수제간식" },
          { title: "져키/스틱" },
          { title: "통살/소시지" },
          { title: "스낵" },
          { title: "캣닢/캣글라스" },
          { title: "음료" },
          { title: "껌" },
          { title: "테린/회식" },
        ],
      },
      {
        title: "고양이 영양제",
        submenu: [{ title: "영양제" }, { title: "건강보조제" }],
      },
      {
        title: "고양이 용품",
        submenu: [
          { title: "캣타워/스크래쳐" },
          { title: "하우스/방석" },
          { title: "급식기/급수기" },
          { title: "의류/패션" },
          { title: "모래/화장실" },
          { title: "미용/목욕" },
          { title: "장난감" },
          { title: "펫캠/가전용품" },
          { title: "이동장/외출용품" },
          { title: "건강 관리" },
          { title: "고양이 도서" },
        ],
      },
      {
        title: "페티켓 산책용품",
        submenu: [
          { title: "배변봉투/삽" },
          { title: "물티슈/크리너" },
          { title: "기저귀/매너벨트" },
          { title: "입마개" },
          { title: "가슴줄/하네스" },
          { title: "목줄" },
          { title: "리드줄" },
          { title: "자동줄" },
          { title: "인식표/목걸이" },
          { title: "이동가방/캐리어" },
        ],
      },
      {
        title: "관상어 용품",
        submenu: [
          { title: "사료" },
          { title: "수초/재배용품" },
          { title: "수조/어항" },
          { title: "약품/수질측정" },
          { title: "모터/여과용품" },
          { title: "수조장식/바닥재" },
          { title: "히터/온도계" },
          { title: "청소도구" },
          { title: "조명" },
          { title: "부화용품/급여기" },
          { title: "관상어 도서" },
        ],
      },
      {
        title: "소동물/가축용품",
        submenu: [
          { title: "조류용품" },
          { title: "토끼/기니피그" },
          { title: "햄스터 용품" },
          { title: "고슴도치용품" },
          { title: "페럿용품" },
          { title: "거북이/달팽이용품" },
          { title: "파충류용품" },
          { title: "장수풍뎅이/곤충용품" },
          { title: "가축사료/용품" },
          { title: "소동물 도서" },
        ],
      },
    ],
  },
  {
    icon: "health",
    title: "헬스/건강식품",
    submenu: [
      { title: "건강기능식품" },
      { title: "성인용 건강식품" },
      { title: "여성용 건강식품" },
      { title: "남성용 건강식품" },
      { title: "임산부 건강식품" },
      { title: "시니어 건강식품" },
      {
        title: "어린이 건강식품",
        submenu: [
          { title: "비타민/미네랄" },
          { title: "홍삼" },
          { title: "칼슘" },
          { title: "유산균/초유" },
          { title: "오메가" },
          { title: "기타 건강식품" },
        ],
      },
      {
        title: "비타민/미네랄",
        submenu: [
          { title: "멀티비타민" },
          { title: "비타민A" },
          { title: "비타민B" },
          { title: "비오틴" },
          { title: "비타민D" },
          { title: "비타민E" },
          { title: "비타민K" },
          { title: "칼슘" },
          { title: "마그네슘" },
          { title: "아연" },
          { title: "철분" },
          { title: "요오드" },
          { title: "더보기" },
        ],
      },
      {
        title: "영양제",
        submenu: [
          { title: "유산균" },
          { title: "루테인" },
          { title: "밀크사슬" },
          { title: "오메가/크릴오일" },
          { title: "DHA" },
          { title: "코엔자임Q10" },
          { title: "히알루론산/콜라겐" },
          { title: "효소" },
          { title: "폴리코사놀" },
          { title: "글루코사민" },
          { title: "프로폴리스" },
          { title: "쏘팔메토" },
          { title: "보스웰리아" },
          { title: "더보기" },
        ],
      },
      {
        title: "허브/식물추출물",
        submenu: [
          { title: "석류" },
          { title: "아사이베리" },
          { title: "크랜베리" },
          { title: "블루베리" },
          { title: "클로렐라" },
          { title: "쏘팔메토" },
          { title: "루테인" },
          { title: "빌베리" },
          { title: "프로폴리스" },
          { title: "로얄젤리/벌화분" },
          { title: "밀크사슬" },
          { title: "징코" },
          { title: "마카" },
          { title: "더보기" },
        ],
      },
      {
        title: "홍삼/인삼",
        submenu: [
          { title: "홍삼농충액/홍삼정" },
          { title: "홍삼진액/파우치" },
          { title: "홍삼정과/절편" },
          { title: "홍삼캡슐" },
          { title: "홍삼환" },
          { title: "홍삼캔디/젤리" },
          { title: "어린이홍삼" },
          { title: "기타 홍삼" },
          { title: "인삼/수삼/장뇌삼" },
        ],
      },
      {
        title: "건강즙/음료",
        submenu: [
          { title: "배즙/도라지즙" },
          { title: "양배추즙" },
          { title: "비트/호박즙" },
          { title: "ABC/석류/사과/포도" },
          { title: "양파즙/마늘즙" },
          { title: "기타건강즙" },
          { title: "건강음료" },
        ],
      },
      {
        title: "꿀/프로폴리스",
        submenu: [
          { title: "일반꿀" },
          { title: "벌집꿀" },
          { title: "로얄젤리" },
          { title: "허니파우더/벌화분" },
          { title: "프로폴리스" },
        ],
      },
      {
        title: "건강분말/건강환",
        submenu: [{ title: "건강환" }, { title: "건강분말" }],
      },
      {
        title: "헬스보충식품",
        submenu: [
          { title: "프로틴" },
          { title: "크레아틴" },
          { title: "아미노산" },
          { title: "기타헬스보조제" },
        ],
      },
      {
        title: "다이어트/이너뷰티",
        submenu: [
          { title: "탄수화물차단제" },
          { title: "체지방감소제" },
          { title: "다이어트 쉐이크" },
          { title: "과일/야채음료" },
          { title: "히알루론산/콜라겐" },
          { title: "석류" },
          { title: "기타다이어트식품" },
        ],
      },
      { title: "더보기" },
    ],
  },
  {
    icon: "travel",
    title: "여행/티켓",
    submenu: [
      { title: "여행 홈 바로가기" },
      { title: "국내여행" },
      { title: "펜션/캠핑" },
      { title: "호텔/리조트" },
      {
        title: "티켓/패스",
        submenu: [
          { title: "스키/눈썰매장" },
          { title: "스파/온천/워터파크" },
          { title: "테마파크" },
          { title: "액티비티/레저" },
          { title: "제주관광지" },
          { title: "골프" },
          { title: "유람선/요트/승선권" },
          { title: "공연/전시" },
          { title: "호텔뷔페/바비큐" },
          { title: "키즈파크/키즈체험" },
          { title: "테마카페/여행편의" },
          { title: "체험/원데이클래스" },
        ],
      },
      {
        title: "렌터카",
        submenu: [{ title: "제주렌터카" }, { title: "전국렌터카" }],
      },
      {
        title: "패키지여행/항공",
        submenu: [
          { title: "제주항공권" },
          { title: "제주여행" },
          { title: "내륙버스여행" },
          { title: "내륙기차여행" },
          { title: "섬여행" },
        ],
      },
      { title: "해외여행" },
      {
        title: "패키지여행",
        submenu: [
          { title: "동남아시아/방콕/싱가포르" },
          { title: "일본" },
          { title: "괌/사이펀/호주" },
          { title: "유럽" },
          { title: "대만/홍콩/마카오" },
          { title: "미주/기타" },
        ],
      },
      {
        title: "자유여행/항공",
        submenu: [
          { title: "동남아시아/방콕/싱가포르" },
          { title: "괌/사이판/호주" },
          { title: "유럽/미주/하와이" },
          { title: "대만/홍콩/마카오" },
          { title: "추천 항공권" },
        ],
      },
      {
        title: "티켓/패스/현지투어",
        submenu: [
          { title: "동남아시아/방콕/싱가포르" },
          { title: "일본" },
          { title: "괌/사이판/호주" },
          { title: "유럽" },
          { title: "미주/하와이" },
          { title: "대만" },
          { title: "홍콩/중국/마카오" },
        ],
      },
      { title: "호텔" },
      { title: "실시간항공권" },
    ],
  },
  {
    icon: "theme",
    title: "테마관",
    submenu: [
      { title: "22 겨울 패션 스토어" },
      { title: "로켓설치" },
      { title: "공간별 집꾸미기" },
      { title: "헬스케어 전문관" },
      { title: "쿠팡 Only" },
      {
        title: "싱글라이프",
        submenu: [
          { title: "청소기/소형가전" },
          { title: "세제/화장지" },
          { title: "샤워/세안" },
          { title: "세탁/청소용품" },
          { title: "방범/호신용품" },
          { title: "샐러드/시리얼" },
          { title: "즉석식품/라면" },
          { title: "반찬/간편조리식품" },
          { title: "간식/베이커리" },
        ],
      },
      { title: "악기전문관" },
      {
        title: "결혼준비",
        submenu: [
          { title: "가전" },
          { title: "가구/침구" },
          { title: "주방용품" },
          { title: "인테리어/소품" },
          { title: "웨딩촬영" },
          { title: "이벤트용품" },
          { title: "웨딩케어" },
        ],
      },
      {
        title: "아트/공예",
        submenu: [
          { title: "미술/화방용품" },
          { title: "DIY소품만들기" },
          { title: "손뜨개/자수" },
          { title: "옷만들기/미싱" },
          { title: "데코/포장용품" },
          { title: "파티/이벤트" },
          { title: "미술/DIY도서" },
          { title: "정리/수납용품" },
        ],
      },
      {
        title: "홈까페",
        submenu: [
          { title: "원두/커피" },
          { title: "커피믹스" },
          { title: "차/티백" },
          { title: "카페시럽" },
          { title: "커피머신/커피메이커" },
          { title: "티포트/전기포트" },
          { title: "제빙기/블렌더" },
          { title: "로스터/그라인더" },
          { title: "커피머신 액세서리" },
          { title: "드랍커피용품" },
          { title: "라떼용품" },
          { title: "티용품" },
          { title: "컵/잔/텀블러" },
          { title: "더보기" },
        ],
      },
      {
        title: "실버스토어",
        submenu: [
          { title: "활동보조" },
          { title: "위생/변기용품" },
          { title: "목욕보조" },
          { title: "건강관리" },
          { title: "재활/운동기구" },
          { title: "간병/보조용품" },
          { title: "병원/의료용품" },
          { title: "생활편의" },
          { title: "의류/신발" },
          { title: "온수/전기매트" },
          { title: "환자식/건강식품" },
          { title: "안전용품" },
          { title: "식사관련용품" },
        ],
      },
    ],
  },
];

const Category = () => {
  const [dropdown, setDropdown] = useState(false);

  const onMouseEnter = () => {
    setDropdown(true);
  };

  const onMouseLeave = () => {
    setDropdown(false);
  };

  return (
    <div
      className={styles["category"]}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
    >
      <p className={styles["category--p"]}>카테고리</p>
      {dropdown && (
        <ul className={styles["menus"]}>
          {categoryItems.map((menu, idx) => {
            const depth = 0;
            return <CategoryItems items={menu} key={idx} depth={depth} />;
          })}
        </ul>
      )}
    </div>
  );
};

export default Category;
