import { useState } from "react";
import AdsItems from "../Advertisement/AdsItems";
import styles from "./CategoryItemList.module.css";

const items = {
  "woman-clothes": [
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/00.jpg`),
      title: "박군 여성용 픽셀캐릭터 10족 양말세트",
      discount: 0,
      price: 15400,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/01.jpg`),
      title:
        "빛나나 은침 실버침 데일리 심플 귀걸이 [ Y569 블랙 네모 골드 큐빅 DO 링 ]",
      discount: 0,
      price: 9800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/02.jpg`),
      title: "위지이버 여성 겨울양말 수면양말 세트 5개묶음",
      discount: 0,
      price: 7900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/03.jpg`),
      title: "소프트홀릭 여성용 두건",
      discount: 0,
      price: 12670,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/04.jpg`),
      title:
        "어썸메이드 여성 장목 포인트 우주 스타 플라워 기본 양말 8켤레 세트",
      discount: 0,
      price: 15000,
      badge: "jet_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/05.png`),
      title: "메이투 비치 숄스카프 T타입",
      discount: 0,
      price: 15900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/06.jpg`),
      title: "1+1 메이투 부들부들한 다용도 디자인 스카프숄",
      discount: 0,
      price: 24900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/07.jpg`),
      title: "미스21 메이비 바나나핀 헤어핀 머리핀 4개 세트 (hp790)",
      discount: 0,
      price: 16900,
      badge: "jet_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/08.jpg`),
      title: "밀라숀 여성 가죽장갑 MS-W-1204L 겨울장갑 양가죽",
      discount: 0,
      price: 20800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/09.jpg`),
      title: "GGRN 여성용 디자인 패션 양말 5켤레 세트",
      discount: 0,
      discount_type: "와우할인가",
      price: 12400,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/10.jpg`),
      title: "블랙마틴싯봉 여성 가죽 손목시계 BKL1721L",
      discount: 0,
      price: 39900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/woman-clothes/list/11.jpg`),
      title: "DH쇼핑 데일리 에잇센스 여성 니삭스",
      discount: 0,
      price: 1790,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  "man-clothes": [
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/00.jpg`),
      title: "주얼리로망 테서렉트 스페이스 써지컬스틸 남자반지 반지",
      discount: 0,
      price: 32500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/01.jpg`),
      title:
        "[더빅보스] JI-5 캐주얼 스판 청바지 _ 슬림핏 세련된 디자인 영 데님 바지 빅사이즈 28~38 사이즈",
      discount: 0,
      price: 22800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/02.jpg`),
      title: "남자 인기컴포트화 캐쥬얼 남성슈즈 소가죽 SP-27-00",
      discount: 0,
      price: 82000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/03.jpeg`),
      title:
        "토핀 TOPIN 브라운 체크 페도라 중절모 신사모자 명절선물 설 선물 남자모자",
      discount: 0,
      price: 27500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/04.jpg`),
      title: "릴렉시즘 기모 조거",
      discount: 0,
      price: 36900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/05.jpg`),
      title: "남자 가죽장갑 터치 방한 겨울 기모 남성 가죽 장갑",
      discount: 0,
      price: 12800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/06.png`),
      title: "네씨 스트레치 버클벨트",
      discount: 0,
      price: 25900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/07.jpg`),
      title: "브라이트 글래시스 빅사이즈 선글라스 Magna",
      discount: 0,
      price: 35000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/08.jpg`),
      title: "그루비 양말선물세트 2켤레 (남성B-골지)",
      discount: 0,
      price: 9400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/09.jpg`),
      title: "비버리힐즈 폴로 클럽 클래식 코튼 카라 티셔츠 ~4XL 빅사이즈",
      discount: 0,
      price: 29900,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/10.jpg`),
      title: "엘라모 기모H TOM 후드티 남녀공용 M~4XL 빅사이즈",
      discount: 0,
      price: 35800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/man-clothes/list/11.jpg`),
      title: "핫코드 남성용 캐주얼 남방 오버핏 빅사이즈 체크 셔츠",
      discount: 0,
      price: 17800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  beauty: [
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/00.jpg`),
      title:
        "맑을담 바르는 botox 아세틸헥사펩타이드 500ppm 10ml 앰플 원액, 단품",
      discount: 0,
      price: 4500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/01.jpg`),
      title: "아도렐 시그니쳐 글리터젤 16ml, ADR064, 1개",
      discount: 0,
      price: 16500,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/02.jpg`),
      title:
        "맑을담 히알루론산 1% 원액 100ml 수용액 고분자/저분자 액상으로 피부침투에 효과적 비누베이스/기타재료, 고분자 100ml",
      discount: 0,
      price: 2900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/03.jpg`),
      title:
        "겟잇뷰티 미백 톤업크림 원데이화이트너120ml+40ml세트 화이트닝로션 색소침착 기미, 1개, 120ml",
      discount: 0,
      price: 15900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/04.jpg`),
      title:
        "닥터비타 기미 잡티 미백 주름 집중케어 저자극 비타민 AC 스킨 토너 200ml, 5개",
      discount: 0,
      price: 67800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/05.jpg`),
      title:
        "스위스녹스 셀프 네일 인조 손톱 연장 재료 온도 열 반응 폴리젤 15ml, 1개, 스카이블루",
      discount: 0,
      price: 78080,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/06.jpeg`),
      title: "[라벨영]쇼킹허브워시오프팩 1+1, 쇼킹허브워시오프팩 1+1",
      discount: 0,
      price: 25900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/07.jpg`),
      title: "예지후 로얄젤리 5종 화장품세트, 1세트",
      discount: 0,
      price: 35000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/08.jpg`),
      title:
        "소티스 모이스춰라이징 수분앰플 2ml X20ea+수분앰플 10ea+앰플안전캡3개+화장솜",
      discount: 0,
      price: 9400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/09.jpg`),
      title: "반디 네일큐어 핑크다이아 세럼물 미니",
      discount: 0,
      price: 29900,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/10.jpg`),
      title: "오르제나 비타민C 브라이트 세럼, 45ml, 1개",
      discount: 0,
      discount_type: "와우할인가",
      price: 35800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/beauty/list/11.jpg`),
      title: "셀비엔 갈락토미세스미스트 155ml, 1병, 1개",
      discount: 0,
      price: 17800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  child: [
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/00.png`),
      title:
        "스펙트라 S2+ 전동유축기 2020 최신모델 바로사용가능 풀구성 (유축기소모품+젖병/젖꼭지포함), 1.S2+(유축기소모품+젖병포함 즉시사용)",
      discount: 0,
      price: 12800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/01.jpg`),
      title: "나뚜라하우스 꾸찌올로 페이스앤바디밀크 유아로션",
      discount: 0,
      price: 17820,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/02.jpg`),
      title:
        "고서임의 천일염 300g 함초소금 택1 은비산호 나비매듭 답례품, 1개, 은비산호 함초소금 300g",
      discount: 0,
      price: 4400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/03.jpg`),
      title:
        "뿌띠슈 어린이용 세이프 베이비 마일드 선쿠션 SPF50+ PA++++, 15g, 1개",
      discount: 0,
      price: 21400,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/04.jpg`),
      title:
        "미아방지목걸이 호랑이띠 미아방지팔찌 에폭호랑이 실버 미아방지세트 조카선물 돌선물 키즈목걸이 키즈팔찌 두돌선물 여아선물 남아선물 주니어목걸이 아이목걸이 어린이팔찌 어린이목걸이, 3. 팔찌",
      discount: 0,
      price: 41000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/05.jpg`),
      title: "로하스베베 페이셜 크림(유기농페이셜수분크림)",
      discount: 0,
      price: 38600,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/06.jpg`),
      title: "루치펠로 멜레멜레 어린이 저불소 치약, 60g, 3개",
      discount: 0,
      price: 16980,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/07.jpg`),
      title: "[유기농] 까띠에 베이비 모이스춰라이징 크림, 75ml, 1개",
      discount: 0,
      price: 14700,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/08.jpg`),
      title: "비단장이 전통문양 천연비누, 07. 6구 박스세트포장, 1개",
      discount: 0,
      price: 26000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/09.jpg`),
      title: "틴더버드 보습 신생아 유아 아기크림 베이비 크림 150ml 2개",
      discount: 0,
      discount_type: "와우할인가",
      price: 58500,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/10.jpg`),
      title: "HBP 와이드형 PES150ml 젖병세트, S (신생아~3개월), 투명",
      discount: 0,
      price: 12520,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child/list/11.jpg`),
      title:
        "성실오색국수 / 국사보자기 포장 / 화이트박스 [400g] 답례품, 04. 오색국수 400g[국사보자기/카키색/]",
      discount: 0,
      price: 5400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  food: [
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/00.jpg`),
      title: "풀무원건강생활 혈압케어 코엔자임Q10, 1개, 60정",
      discount: 0,
      price: 28950,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/01.jpg`),
      title: "바를정 양배추정 1개, 200정, 양배추환",
      discount: 0,
      price: 22310,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/02.jpg`),
      title: "포뉴 철분, 60정, 1개",
      discount: 0,
      price: 33000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/03.jpg`),
      title:
        "A[공주네농장] 새벽이슬맺힌 안동꿀사과 ~할인특가판매 행사중~, 1박스, 05. 가정용 흠과 5KG / 중과",
      discount: 0,
      price: 22000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/04.jpg`),
      title:
        "1+1 엔바디 웨이프로틴 고함량 단백질보충제 /아미노400 증정, 2kg, 2개",
      discount: 0,
      price: 68400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/05.jpg`),
      title:
        "[종근당건강] 프리미엄 오메가3 플러스 6개월분 건강식품 영양제 부모님 효도선물 추석선물 명절선물 선물세트 설날선물 어버이날선물 부모님선물 아빠선물 엄마선물 아버지선물 어머니선물, 1박스",
      discount: 0,
      price: 32900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/06.png`),
      title: "그린스토어 보라지 감마리놀렌산, 1개, 60정",
      discount: 0,
      price: 28100,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/07.jpg`),
      title:
        "뉴트리원 흡수율 높은 비타민D3 3000IU 초소형캡슐 DSM사 비타민D 뼈건강 항산화 2중기능성, 60정, 6개",
      discount: 0,
      discount_type: "즉시할인가",
      price: 75900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/08.jpg`),
      title: "마이밀 마시는 뉴프로틴, 190ml, 1박스",
      discount: 0,
      price: 17200,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/09.jpg`),
      title:
        "마켓통 연지홍게 13마리 포항 구룡포 산지직송 비품연지홍게(가성비 실속형 라면용 홍게), 연지 홍게 13마리 내외(비품)",
      discount: 0,
      discount_type: "와우할인가",
      price: 17820,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/10.jpg`),
      title: "호두 캘리포니아 햇호두 (2022년 최근통관) 1kg 최근생산, 1팩",
      discount: 0,
      price: 13800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/food/list/11.jpg`),
      title: "쎈트힐 제일와이 Y유산균 15g, 30정, 2개",
      discount: 0,
      price: 33930,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
  ],
  kitchen: [
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/00.jpeg`),
      title:
        "커피 스탠실 라떼아트 라떼 틀 무늬 도안 라떼아트만들기 장식 19 pcs 커피 스텐실 멋진 커피 인쇄 모델 거품 스프레이 케이크 스텐실 커피 드로잉 카푸치노 몰드 가루 체 도구, 그림으로",
      discount: 0,
      price: 13200,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/01.png`),
      title: "테팔 PTFE G6 원픽냄비팬, 420 x 220 x 105 mm, 양송이 베이지",
      discount: 0,
      price: 29800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/02.jpg`),
      title:
        "[KT알파쇼핑][7호세트] 땡스소윤 시즌3 냉동실 용기 7호 10개 세트, 색상:쿨 라벤더",
      discount: 0,
      discount_type: "즉시할인가",
      price: 38280,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/03.jpg`),
      title: "아이지 소맥탕탕 제조기, 펭귄, 1개",
      discount: 0,
      price: 7100,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/04.jpg`),
      title: "미소담은 무선진공쌀통 25kg 대용량 쌀보관함",
      discount: 0,
      price: 129000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/05.jpg`),
      title: "형창플라스틱 젓갈통 180g ~ 1kg 당일발송, 180g팔각",
      discount: 0,
      price: 460,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/06.jpg`),
      title: "행자공예 제기 세트 21/37P/47P, 물푸레 간소제기",
      discount: 0,
      price: 185000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/07.png`),
      title: "유앤팩 TY 밀폐 사각 죽용기 대 50개 (900ml) + 뚜껑포함, 3개",
      discount: 0,
      price: 38000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/08.jpg`),
      title: "모던 도자기 골드라인 4구 나눔접시 접시 식판",
      discount: 0,
      price: 10600,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/09.jpg`),
      title: "인블룸 1+1set 스텐430 물빠짐 회전 조리도구통, 2개입",
      discount: 0,
      price: 23800,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/10.jpg`),
      title: "티온스 T09 콜드컵 스텐 보온병, 블랙, 1.1L",
      discount: 0,
      price: 16230,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/kitchen/list/11.jpg`),
      title:
        "[1+1]국내산 대만 수출 브랜드 원더마마 프라이팬 28cm+프라이팬 28cm 2개 세트 '사은품 증정' ( 평일 오후 4시 이전 주문건 당일 발송 )",
      discount: 0,
      price: 24900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  living: [
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/00.jpg`),
      title: "셀프줄눈마켓 바닥용 타일 줄눈 코팅제 실버펄 100g, 1세트",
      discount: 0,
      price: 12500,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/01.jpg`),
      title: "노즈퓨리 코세척기 + 세정용 분말 10p + 60p x 2개, 1세트",
      discount: 0,
      price: 20880,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/02.jpg`),
      title:
        "다봉쓰 미용실 극손상 9% 단백질 트리트먼트 600ml (베이비 파우더향)",
      discount: 0,
      price: 48900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/03.jpg`),
      title: "한라비 일회용 은박 냄비 KJ-01442, 10개",
      discount: 0,
      price: 10740,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/04.jpg`),
      title:
        "팸퍼스 베이비드라이 엑스트라 흡수 팬티형 기저귀 아동공용 4단계(9~14kg), 180매",
      discount: 0,
      discount_type: "와우할인가",
      price: 57900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/05.jpg`),
      title:
        "우디홈 원목 스탠드 옷걸이 스텐드 행거 이동식 인테리어, 엣지형 브라운",
      discount: 0,
      price: 39900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/06.jpg`),
      title: "피티즘 밀대걸레 + 극세사 전용패드 4p 세트, 1세트",
      discount: 0,
      price: 10800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/07.jpg`),
      title: "르메이드 스테인레스 음식물 쓰레기통, 화이트",
      discount: 0,
      price: 37340,
      badge: "jet_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/08.jpg`),
      title: "피죤 레귤러 섬유유연제 옐로미모사 리필, 2.3L, 2개",
      discount: 0,
      price: 5960,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/09.jpg`),
      title: "바디공식 2단 압박 무릎보호대, 1개",
      discount: 0,
      price: 13800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/10.jpg`),
      title: "조이월드 스텐 미니 식기건조대 2단, 은색",
      discount: 0,
      price: 18400,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/living/list/11.jpg`),
      title: "디오셀 현관정리 다용도 벽걸이 선반 행거, 그레이, 1개",
      discount: 0,
      discount_type: "와우할인가",
      price: 10690,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
  ],
  interior: [
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/00.jpg`),
      title: "라셀렌 폴란드 80 컬러 구스다운 이불, 네이비",
      discount: 0,
      price: 376570,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/01.jpg`),
      title:
        "원세븐나인 모던부티크 헤링본 패브릭 샤워커튼 1800mm x 1880mm, 1개, 화이트계열",
      discount: 0,
      price: 38000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/02.jpg`),
      title:
        "[윈홈스](당일발송 맞춤커튼)이음선과 비침 없는 오염방지 도톰 쉬폰 나비주름 커튼/안심케어 커튼",
      discount: 0,
      price: 65800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/03.jpg`),
      title: "아토앤알로 쉐이프 항균 토퍼, 화이트",
      discount: 0,
      price: 60270,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/04.jpg`),
      title: "슈가맘 TPU 방수식탁보, 리프 나뭇잎, 6인(145 x 220cm)",
      discount: 0,
      price: 31890,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/05.jpg`),
      title: "MJK 모던샤인 무소음 벽시계 300, 화이트로즈골드",
      discount: 0,
      price: 9800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/06.jpg`),
      title:
        "월플랜 만능 풀바른벽지 셀프도배 합지 벽지, 만능풀바른벽지, 240cmX(필수! 제품번호 결제창에서 입력)",
      discount: 0,
      discount_type: "와우할인가",
      price: 6840,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/07.jpg`),
      title: "3단 접이식 3D 메모리폼 바닥 침대 토퍼 매트리스 12센치",
      discount: 0,
      price: 229000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/08.jpg`),
      title: "마켓플랜 데스크 서랍 정리함, 네이비, 옐로우, 오렌지, 민트, 4개",
      discount: 0,
      price: 14900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/09.jpg`),
      title: "디오셀 현관정리 다용도 벽걸이 선반 행거, 그레이, 1개",
      discount: 0,
      discount_type: "와우할인가",
      price: 10690,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/10.jpg`),
      title:
        "아란아트 호랑이그림액자 수맥차단 액운방지 사무실 거실벽인테리어, 07.백호랑이",
      discount: 0,
      discount_type: "와우할인가",
      price: 69610,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/interior/list/11.jpg`),
      title: "쿠션마루 빈블래스트 관절보호 쿠션 실내화, 혼합색상",
      discount: 0,
      price: 11490,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
  ],
  digital: [
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/00.jpg`),
      title: "비타그램 글램팡 가슴마사지기, VG-BM21, 핑크",
      discount: 0,
      price: 55840,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/01.jpg`),
      title:
        "팜트리 갤럭시A31 A315 케이스 5만원펼쳐서수납/카드빠짐방지기능/스트랩제공/ 팜트리케이스",
      discount: 0,
      price: 16900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/02.jpg`),
      title:
        "[후지카] 뉴터보 전기온풍기/전기히터/전기난로 레드 FU-4733/골드 FU-4766/아이 FU-4788/실버 FU-2077, FU-4766(골드)",
      discount: 0,
      price: 238000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/03.png`),
      title:
        "23년형 NEW 까르페 물걸레 로봇청소기 PRO 미디어 4000PA 강력흡입 청소기(무선 리모컨 증정) 화이트, i5C-W",
      discount: 0,
      discount_type: "즉시할인가",
      price: 299000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/04.jpg`),
      title: "KST 나무 핸드폰 케이스",
      discount: 0,
      price: 14500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/05.jpg`),
      title:
        "10.1 인치 디스플레이 해상도 1280 ＊ 800 LCD 크기 : CTP 터치 I2C 인터페이스가있는 229.46 ＊ 149.1 ＊ 4....",
      discount: 0,
      price: 139700,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/06.jpg`),
      title: "와이넷 원터치세탁기호스, 1개, 원터치세탁기호스5M냉온수세트",
      discount: 0,
      price: 32400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/07.jpg`),
      title: "내셔널지오그래픽 로고 패치 스트랩 더블 프로텍티브 휴대폰 케이스",
      discount: 0,
      discount_type: "즉시할인가",
      price: 25800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/08.jpg`),
      title: "갤럭시 S22 커스텀 주문제작 휴대폰스킨 보호필름 1매, 단품",
      discount: 0,
      price: 15050,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/09.jpg`),
      title:
        "부엉이눈 야외감시카메라 C5 휴대용이동식 농작물야생동물관찰용 cctv 야적장 창고 야간적외선 관공서납품, lcd 없음(32gb)",
      discount: 0,
      price: 85000,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/10.jpg`),
      title:
        "블레이즈 C to C 케이블 100W 20V 5A 초고속 충전케이블 데이터전송 PD100, 25cm",
      discount: 0,
      price: 5900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/digital/list/11.jpg`),
      title: "솔츠 아이폰12프로맥스 범퍼 슬라이드 핸드폰 카드케이스",
      discount: 0,
      price: 16000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  sports: [
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/00.jpg`),
      title: "카시야 쿨 실리콘 양손 캐디용 네일 반장갑, 여성용",
      discount: 0,
      price: 7920,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/01.jpg`),
      title:
        "카타나 프리미엄 골드 V2 고반발 여성 유틸리티우드, 선택완료, 21도 L",
      discount: 0,
      price: 199000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/02.jpg`),
      title:
        "발열패드 화끈한 100도씨 핫팩 무릅담요 내복 신반 따뜻함이 필요한곳 diy 5피스 발열판 방한복 3단조절 usb 방수 발열 보온 발열조끼",
      discount: 0,
      discount_type: "와우할인가",
      price: 8270,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/03.jpg`),
      title: "[남도드림] 대나무터 국산 대나무 숯 캠핑용 1kg, 단품",
      discount: 0,
      price: 8900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/04.jpg`),
      title:
        "바디턴 스윙 연습기 골프치킨윙 골프몸통스윙 분석기, 장타로 골프 스윙연습기_옐로우",
      discount: 0,
      price: 34500,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/05.jpg`),
      title: "버프 드라이플릭스 햇 버프, R_BLACK 118099.999.10",
      discount: 0,
      price: 32000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/06.jpg`),
      title:
        "TOTOELY 골프 일자 블레이드 퍼터 커버 남성 여성 슈즈 신발 디자인 자석 헤드 카바, 레드",
      discount: 0,
      price: 19900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/07.png`),
      title: "네온사인 릴대끝보기 녹색 적색 전자케미 오토케미",
      discount: 0,
      price: 4200,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/08.jpg`),
      title: "360이지볼라이너+SUM클립 볼타월, 레드",
      discount: 0,
      price: 25000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/09.jpg`),
      title: "골프볼라이너 마커펜, 블랙",
      discount: 0,
      price: 1200,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/10.jpg`),
      title:
        "빅 넘버링 골프 아이언 헤드 커버 (Big Numbering Golf Iron Head Cover), 화이트&컬러넘버",
      discount: 0,
      price: 16900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/sports/list/11.jpg`),
      title:
        "나라샵 UST 꼴뚜기 대구채비 어시스트훅 세이코 바늘 40호 외바늘 쌍바늘채비 대구바늘, 화이트꼴뚜기3개입",
      discount: 0,
      price: 2500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  car: [
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/00.jpg`),
      title:
        "아르띠콜로 차량용 수납함 차량뒷자석수납 필수차량용품 차량틈새수납 아이디어 차량용품 첫차선물 차량용 거치대, acl 다이아몬드 핑크",
      discount: 0,
      price: 15960,
      badge: "jet_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/01.png`),
      title: "프루젠 차량용 인버터 차박 캠핑 시거잭",
      discount: 0,
      price: 51900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/02.jpg`),
      title:
        "6발 대부(The Godfather) 뮤직 에어크락션 (12V전용) 에어혼 자동차혼 오토바이혼 튜닝혼 차량용 경음기, 6발 대부 에어혼(12V)",
      discount: 0,
      price: 47500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/03.jpg`),
      title: "자동차 차량용 카본 범퍼가드 (2개1세트)",
      discount: 0,
      price: 6200,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/04.jpg`),
      title:
        "올뉴 카니발 45발 LED 방향지시등 브레이크등 미등, 화이트 싱글 2개1세트",
      discount: 0,
      price: 15000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/05.jpg`),
      title: "NGK 점화플러그 이리듐플러그 SILZKR6B10E, 1박스(4개입)",
      discount: 0,
      price: 27600,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/06.jpg`),
      title: "전문가용 극세사 중벌 마무리용 터치 드라잉 세차 타올 40/60, 10장",
      discount: 0,
      price: 19900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/07.jpg`),
      title: "VIP 올뉴모닝 대쉬보드커버 리무진엠보, 와인, 2017모닝(JA)",
      discount: 0,
      price: 49500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/08.jpg`),
      title:
        "볼보 C40 S60 S90 V60 V90 XC40 XC60 XC90 키케이스 가죽 TPU 키커버 키홀더, 화이트-상품설명확인-우측3버튼",
      discount: 0,
      price: 16900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/09.jpg`),
      title: "VIP 에어로뷰 와이퍼 2개 1세트, 650mm",
      discount: 0,
      price: 10500,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/10.jpg`),
      title: "오토윈 뒷좌석 열선 온열 시트 24V 자동차 전기장판, 검정",
      discount: 0,
      price: 35000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/car/list/11.jpg`),
      title: "그랜져HG 블랙에디션 21발 LED 안개등 H8, H8 타입 2개 1세트",
      discount: 0,
      price: 28000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  hobby: [
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/00.jpg`),
      title: "캔들바다 올리브시어버터 비누베이스 1kg (투명 백색), [ 백색 ]",
      discount: 0,
      price: 4500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/01.jpg`),
      title: "닥터뮤즈 컬러 통기타현 6종 3세트, 22W1573",
      discount: 0,
      price: 11800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/02.jpg`),
      title: "와이든 바이올린 악기 입문 연습용 4/4, 22W1585, 브라운 + 블랙",
      discount: 0,
      price: 159000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/03.jpg`),
      title:
        "[말씀타올]주기도문 사도신경 타올 수건선물세트 2P, 쇼핑백추가, 고급케이스+리본",
      discount: 0,
      price: 11430,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/04.jpg`),
      title: "와이든 디지털 피아노 키보드 54 / 61 건반용 받침 Z형 스탠드, 블랙",
      discount: 0,
      price: 25800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/05.jpg`),
      title:
        "[말씀타올]주기도문 사도신경 십계명 수건선물세트 3P, 쇼핑백추가, 고급케이스+리본",
      discount: 0,
      price: 16770,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/06.jpg`),
      title: "고정볼 누름볼 2mm, 실버",
      discount: 0,
      price: 1000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/07.jpg`),
      title:
        "코리아씨밀락 골든 호호바오일 직수입 초특가, 골든 호호바오일 500ml",
      discount: 0,
      price: 25000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/08.jpg`),
      title:
        "와이든 스틸 텅드럼 핸드팬 악기 행팬 행드럼 탱크, 8음계(15.24센치미터)",
      discount: 0,
      price: 27000,
      badge: "jet_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/09.jpg`),
      title: "와이든 우쿨렐레 스트랩 어깨끈",
      discount: 0,
      price: 7900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/10.jpg`),
      title: "코리아씨밀락 정제 로즈힙오일, 정제 로즈힙오일 50 ml",
      discount: 0,
      price: 6000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/hobby/list/11.jpg`),
      title:
        "맑을담 라우릴글루코사이드 100ml 천연계면활성제 비누베이스/기타재료, 라우릴글루코사이드100ml",
      discount: 0,
      price: 2500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  office: [
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/00.jpg`),
      title: "사이언쌤 쌤에어로켓발사대(카트형)",
      discount: 0,
      price: 300000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/01.jpg`),
      title:
        "아이소핑크 특호 압출법단열재 /압출법보온판 70T ~100T, 한영 아이소핑크 특호100T 600x900 1장",
      discount: 0,
      price: 24000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/02.jpg`),
      title:
        "LED간판 영업중간판 오픈간판 아크릴간판 식당간판 미니간판 카페간판 전광판 led보드 네온사인 포맥스 잔coffee 75x25cm",
      discount: 0,
      price: 89000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/03.jpeg`),
      title:
        "나일론 페인팅 브러쉬 아크릴붓 24종 페인팅나이프 아크릴 유화 수채화 붓, 그레이",
      discount: 0,
      price: 25800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/04.png`),
      title: "예피아 주문제작 유리대용 PVC 투명매트, 투명",
      discount: 0,
      price: 100,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/05.jpg`),
      title:
        "회색스티로폼 네오폴 비드법단열재 600 x 900(20T~100T)mm 택 1, 30T_600×900(2장)",
      discount: 0,
      price: 14200,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/06.jpg`),
      title: "헤렌드 FCH-9200 (너구리) 4조 세트 거친 붓",
      discount: 0,
      price: 31000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/07.jpg`),
      title:
        "디자인후니 계단광고(6장1세트) 계단광고표찰 계단홍보용 계단광고홍보용 계단광고판",
      discount: 0,
      price: 35000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/08.png`),
      title:
        "DISSHOP 모자를 구김없이 보관해주는 타원형모자보관튜브 5p, 새것같이 모자를 보관할수 있는 원형모자튜브",
      discount: 0,
      price: 10500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/09.jpg`),
      title: "디피제로 철제 L배너 600 x 1800 mm, 블랙, 1개",
      discount: 0,
      price: 30500,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/10.jpeg`),
      title:
        "크리스탈명패 대표이사 교장교감 공인중개사 변호사 세무사 명패제작 교회명패[0017068]",
      discount: 0,
      price: 110000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/office/list/11.jpg`),
      title: "도장마트 만년스탬프, 사업자 명판 (윤고딕)",
      discount: 0,
      price: 5000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  book: [
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/00.jpg`),
      title:
        "어도비 프리미어 프로 cc 강좌 USB 책 교재 보다 좋은 교육 유튜브 동영상 만들기 편집 강의",
      discount: 0,
      price: 26700,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/01.jpg`),
      title:
        "아가페 큰글자 성경책 새찬송가 큰글씨 예쁜 개역개정 NKR82AB 특대 성경 1104, 1.NKR82AB 특대 브라운",
      discount: 0,
      price: 58500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/02.jpg`),
      title: "USB 일본어 독학 단어 일본어 회화 Mp3 패키지 (차량 가능)",
      discount: 0,
      price: 73780,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/03.jpg`),
      title: "Vocabulary workshop(보카블러리 워크샵) orange green blue purple",
      discount: 0,
      price: 15300,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/04.jpg`),
      title: "BBC사이언스 1년정기구독, 1년정기구독 23년 2월호~24년 1월호",
      discount: 0,
      price: 126000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/05.jpg`),
      title: "에이든 제주 여행지도 세트 스티커 업(스티커 2매 추가 구성)",
      discount: 0,
      price: 19900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/06.jpg`),
      title:
        "ETS 정기시험 기출문제집 1000 LC RC 2 선택구매, ETS 정기시험 기출문제집 1000 LC - 2",
      discount: 0,
      price: 16020,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/07.jpg`),
      title:
        "화평플러스몰 어린이성경책 컬러 일러스트 어린이성경 주일학교 예배용, 선택9_일러스트어린이_소_고급_청색",
      discount: 0,
      price: 25200,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/08.jpg`),
      title: "엑셀 사용법 기초 활용 강의 USB",
      discount: 0,
      price: 24800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/09.jpg`),
      title: "2022 NCS 은행권 채용시험 금융 경제 경영 상식, 고시넷",
      discount: 0,
      price: 27000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/10.jpg`),
      title:
        "153성경몰 미니 큰글씨 성경책 ( 개역개정 새찬송가 해설 지퍼 ), [중]올리브그린",
      discount: 0,
      price: 36000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/book/list/11.jpg`),
      title:
        "아가페 큰글자성경책 개역개정 새찬송가 큰글씨성경책, 선택9_큰글성경_특대_브라운",
      discount: 0,
      price: 50400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  pets: [
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/00.jpg`),
      title: "퍼피웨건 반려동물 캐리어 겸용 기능성 로얄 유모차, 로얄 네이비",
      discount: 0,
      price: 144480,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/01.jpg`),
      title: "스킨카솔겔 15g 상처 트러블 치료",
      discount: 0,
      discount_type: "와우할인가",
      price: 7260,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/02.jpg`),
      title:
        "펫팀 캣그라스 새싹보리 귀리 밀 고양이식물 재배키트 고양이풀 영양간식, 고양이가 먹는 새싹보리",
      discount: 0,
      price: 5400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/03.jpg`),
      title: "세척볶음 카나리아 씨드 (500g) 앵무새 모이 먹이 사료, 1봉",
      discount: 0,
      price: 5800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/04.jpg`),
      title: "디팡 펫플레이 강아지매트 폴딩타입 140폭, 젤리 라이트 그레이",
      discount: 0,
      price: 21800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/05.jpg`),
      title:
        "올미오펫 올패브릭 강아지 곡선 4단 계단 7컬러 색상선택가능, 올패브릭 브라운 4단 계단",
      discount: 0,
      price: 59900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/06.jpg`),
      title: "에스앤비 코리아 고양이 화장실 고급형, 1개",
      discount: 0,
      discount_type: "와우할인가",
      price: 8640,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/07.jpg`),
      title:
        "냥이마트 고양이 셀프 낚시대 고양이 흥미유발 장난감 천장 접착형, 대왕 애벌레",
      discount: 0,
      discount_type: "와우할인가",
      price: 4410,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/08.jpg`),
      title: "아크내추럴스 브러시리스 서플리먼트 강아지 덴탈껌 미니 113g, 1개",
      discount: 0,
      price: 9710,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/09.jpg`),
      title: "독톡 수컷 강아지 배변판 실내 마킹 방지 가림 수비대, 올리브그린",
      discount: 0,
      price: 12900,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/10.png`),
      title:
        "개 강아지 리드줄 개목줄 마당줄 와이어 줄 개줄 견인, 10M, 1.투명 코팅 와이어, 5mm(대형)",
      discount: 0,
      price: 20300,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/pets/list/11.png`),
      title: "딩동펫 애견 미끄럼방지 매트, 앞면(그레이헤링본), 뒷면(차콜)",
      discount: 0,
      price: 79250,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
  ],
  travel: [
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/00.jpg`),
      title: "[제주 서귀포] 아인스호텔",
      discount: 0,
      price: 50000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/01.jpg`),
      title: "[화성] 신라스테이 동탄",
      discount: 0,
      price: 148300,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/02.jpg`),
      title: "[제주도온수풀] 호텔 토스카나",
      discount: 0,
      price: 264000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/03.jpg`),
      title: "[진주] 제이스퀘어호텔",
      discount: 0,
      discount_type: "와우할인가",
      price: 90990,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/04.jpg`),
      title: "[제주] 호텔 난타",
      discount: 0,
      discount_type: "와우할인가",
      price: 82800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/05.jpg`),
      title: "[삼척시] 코아페바다펜션",
      discount: 0,
      price: 69000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/06.jpg`),
      title: "[부산] 부산 해운대 광안리 요트홀릭 요트투어 승선권",
      discount: 0,
      price: 20000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/07.jpg`),
      title: "[고성군] 고성 펜션바닷가",
      discount: 0,
      price: 60000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/08.jpg`),
      title: "[여수] 여수 HS관광호텔 (여수 HS관광호텔)",
      discount: 0,
      price: 80000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/09.jpg`),
      title: "[속초] 금호리조트 설악",
      discount: 0,
      discount_type: "와우할인가",
      price: 92880,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/10.jpg`),
      title: "[서울/중구] 나인트리 프리미어 호텔 명동2",
      discount: 0,
      price: 108000,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/travel/list/11.jpg`),
      title: "[중구] 호텔 리버사이드 ",
      discount: 0,
      price: 63400,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
  ],
  "child-fashion": [
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/00.jpg`),
      title:
        "까꿍놀이터 기모골지레깅스2종세트 융털안감 보온짱 국내제작 유아동용 겨울바지",
      discount: 0,
      discount_type: "즉시할인가",
      price: 22500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/01.jpg`),
      title: "이라인 여아용 슈가하트 이지웨어 긴팔 잠옷 상하의 세트",
      discount: 0,
      price: 10900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/02.jpg`),
      title: "시리얼랜드 아동용 미디엄삭스 오렌지플렉스 3종 세트",
      discount: 0,
      price: 9800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/03.jpg`),
      title: "[빌도르] 윌리토끼 5매 여아 드로즈 사각 아동 키즈 팬티 세트",
      discount: 0,
      price: 18900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/04.jpg`),
      title: "<가격인하/득템찬스>믹스퐁퐁리본집게핀",
      discount: 0,
      price: 1600,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/05.jpg`),
      title:
        "3+1 러브퀸 곰이네 아동 아기 유아 모자 털모자 귀달이 비니 벙거지 볼캡",
      discount: 0,
      price: 6900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/06.jpg`),
      title: "키즈라인 여아용 러브베리 삼각 팬티 5종 세트",
      discount: 0,
      price: 8900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/07.jpg`),
      title: "아동 유아 겨울양말 방한용 초등학생 두꺼운 기모양말",
      discount: 0,
      price: 11900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/08.png`),
      title: "무지개나무 아동용 옛날교복 코스튬 상하 바지세트",
      discount: 0,
      price: 27900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/09.jpg`),
      title: "릴리앤보니 분리 타이즈",
      discount: 0,
      price: 6700,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/10.jpg`),
      title: "여아용 폭스+프리티 10매입 삼각 팬티",
      discount: 0,
      price: 15900,
      badge: "jet_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/child-fashion/list/11.jpg`),
      title:
        "유니프랜드 아동용 라벤더하트 오가닉 편면 9부 내의 실내복 상하세트",
      discount: 0,
      price: 9900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
  ],
  health: [
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/00.jpg`),
      title:
        "JW중외제약 리얼메디 위건강 총4박스 스페인 감초추출물 헬리코박터균 케어 위점막 보호 7중복합 비타민A 비타민C 비타민E 판토텐산 아연 셀레늄 영양제, 1세트",
      discount: 0,
      price: 41100,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/01.png`),
      title:
        "더클린커피 콜롬비아 수프레모 곰팡이독소 인증 방탄커피원두 200g 340g 500g, 분쇄 안함 (홀빈)",
      discount: 0,
      price: 22900,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/02.jpg`),
      title:
        "이우정한의사의 코숨테이프-입벌림방지 여성 남성 꿀잠아이템 수면루틴, 신제품 코숨테이프 (코네캐릭터 O)",
      discount: 0,
      price: 19500,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/03.png`),
      title: "그린스토어 보라지 감마리놀렌산, 1개, 60정",
      discount: 0,
      price: 28100,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/04.jpg`),
      title: "아임리얼 클래시 플러스 마스크 핑크 중형 KF94, 1개, 20개입",
      discount: 0,
      price: 10120,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/05.jpg`),
      title: "마이밀 마시는 뉴프로틴, 190ml, 1박스",
      discount: 0,
      price: 17200,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/06.jpg`),
      title: "디지지 스마트워치 풀커버 하드 케이스, 투명",
      discount: 0,
      price: 6900,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/07.jpg`),
      title:
        "엔템 가정용 칫솔살균기 빛충전 무선 자외선 칫솔 살균기 면도기살균 반자동 치약짜개 포함",
      discount: 0,
      discount_type: "와우할인가",
      price: 15210,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/08.jpg`),
      title: "호두 캘리포니아 햇호두 (2022년 최근통관) 1kg 최근생산, 1팩",
      discount: 0,
      price: 13800,
      badge: null,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/09.jpg`),
      title:
        "인디에어 유어핏 새부리형 컬러마스크 25매 대형L [9컬러], 유어핏 바이올렛 대형L 25매",
      discount: 0,
      price: 10900,
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/10.jpg`),
      title: "바디공식 2단 압박 무릎보호대, 1개",
      discount: 0,
      price: 13800,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
    {
      img: require(`../../assets/img/categoryBestUnit/health/list/11.jpg`),
      title: "루아러블 갤럭시워치 충전 케이블 무선 충전기 충전독, 블랙",
      discount: 0,
      price: 14000,
      badge: "rocket_delivary",
      review_score: 4.5,
      review_count: 555,
    },
  ],
};

const CategoryItemList = ({ category }) => {
  const [btnHover, setBtnHover] = useState(false);
  const [index, setIndex] = useState(0);

  const offset = 6;
  const totalItems = items[`${category}`].length;
  const maxIndex = Math.ceil(totalItems / offset) - 1;

  const onMouseEnter = () => {
    setBtnHover(true);
  };
  const onMouseLeave = () => {
    setBtnHover(false);
  };

  const increaseIndex = () => {
    setIndex((prev) => (prev === maxIndex ? 0 : prev + 1));
  };
  const decreaseIndex = () => {
    setIndex((prev) => (prev === 0 ? maxIndex : prev - 1));
  };
  const onclick = (index) => {
    setIndex(index);
  };

  let button = btnHover && (
    <>
      <span
        onClick={decreaseIndex}
        className={`${styles["button"]} ${styles["prev"]} `}
      />
      <span
        onClick={increaseIndex}
        className={`${styles["button"]} ${styles["next"]} `}
      />
    </>
  );

  return (
    <div
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      className={styles["items"]}
    >
      {button}
      <ul>
        {items[`${category}`]
          .slice(offset * index, offset * index + offset)
          .map((item, itemIndex) => (
            <AdsItems
              key={itemIndex}
              item_type="bestUnit"
              img={item.img}
              title={item.title}
              discount={item.discount}
              discount_type={item.discount_type}
              price={item.price}
              badge={item.badge}
              review_score={item.review_score}
              review_count={item.review_count}
            />
          ))}
      </ul>
      <ul className={styles["promotion__dot"]}>
        {items[`${category}`].slice(0, maxIndex + 1).map((_, itemindex) => (
          <li
            onClick={() => onclick(itemindex)}
            key={itemindex}
            className={` ${
              index === itemindex ? styles["selected"] : styles["dot"]
            }`}
          ></li>
        ))}
      </ul>
    </div>
  );
};

export default CategoryItemList;
